"""Registry and generated-view Implementation for Development-Agent Governance."""
from __future__ import annotations
import json
import re
from pathlib import Path
from typing import Any, Iterable
from agent_governance_aiml_adoption import registry_contract_errors
from agent_governance_context_specs import context_source_spec_errors, source_name
from agent_governance_registry_budget import registry_budget_errors
from agent_governance_registry_capabilities import registry_capability_errors
from agent_governance_task_control import validate_task_execution_control

REPO_ROOT = Path(__file__).resolve().parents[2]
REGISTRY_REL = Path(".codex/agent_registry_v1.json")
GENERATED_NOTICE = "<!-- GENERATED by agent_governance.py from .codex/agent_registry_v1.json; DO NOT EDIT -->"
GENERATED_TOML_NOTICE = "# GENERATED by agent_governance.py from .codex/agent_registry_v1.json; DO NOT EDIT"
VALID_EXECUTION_MODES = {"Conductor", "Investigator", "Builder", "Verifier"}
VALID_CODEX_TYPES = {"default", "explorer", "worker"}
ROLE_REQUIRED = {
    "execution_mode", "codex_type", "permission", "summary", "lens", "activation",
    "skip_when", "owns", "refuses", "capabilities", "tools", "disallowed_tools",
    "skills", "context_packs", "output", "judgment_rules",
}
REVIEW_ROLES = {"A3", "AI-E", "BB", "CC", "E2", "E3", "E5", "FA", "IB", "MIT", "OPS", "QA", "QC", "R4"}
FICTIONAL_PERSONA_RE = re.compile(
    r"\b(ph\.?d|professor|\d+\+?\s*years?|resume of)\b",
    re.IGNORECASE,
)

def load_registry(path: Path | None = None) -> dict[str, Any]:
    """Load the canonical role registry."""

    registry_path = path or (REPO_ROOT / REGISTRY_REL)
    return json.loads(registry_path.read_text(encoding="utf-8"))


def _iter_text(value: Any) -> Iterable[str]:
    if isinstance(value, str):
        yield value
    elif isinstance(value, dict):
        for nested in value.values():
            yield from _iter_text(nested)
    elif isinstance(value, list):
        for nested in value:
            yield from _iter_text(nested)


def validate_registry(registry: dict[str, Any], root: Path = REPO_ROOT) -> list[str]:
    """Return deterministic validation errors for the registry Interface."""

    errors: list[str] = []
    for key in (
        "schema_version",
        "module",
        "interfaces",
        "context_evidence_schema_path",
        "external_evidence_schema_path",
        "closure_quality_followup_schema_path",
        "closure_quality_attestation_schema_path",
        "permission_enforcement",
        "task_execution_control",
        "authority_classes",
        "external_access_classes",
        "permission_profiles",
        "context_packs",
        "budget_envelopes",
        "capability_packs",
        "effect_adapters",
        "on_demand_skills",
        "workflow_contracts",
        "native_agent_adapters",
        "roles",
    ):
        if key not in registry:
            errors.append(f"registry missing {key}")

    if errors:
        return errors
    if registry["schema_version"] != "agent_registry_v1":
        errors.append("schema_version must be agent_registry_v1")
    if registry["module"] != "development_agent_governance":
        errors.append("module must be development_agent_governance")
    context_schema = registry.get("context_evidence_schema_path")
    if (
        context_schema != ".codex/schemas/context_evidence_artifact_v1.schema.json"
        or not (root / str(context_schema)).is_file()
    ):
        errors.append("context_evidence_schema_path is invalid")
    external_schema = registry.get("external_evidence_schema_path")
    if (
        external_schema != ".codex/schemas/external_evidence_capture_v1.schema.json"
        or not (root / str(external_schema)).is_file()
    ):
        errors.append("external_evidence_schema_path is invalid")
    quality_schemas = {
        "closure_quality_followup_schema_path": ".codex/schemas/closure_quality_followup_v1.schema.json",
        "closure_quality_attestation_schema_path": ".codex/schemas/closure_quality_attestation_v1.schema.json",
    }
    for field, expected_path in quality_schemas.items():
        actual_path = registry.get(field)
        if actual_path != expected_path or not (root / str(actual_path)).is_file():
            errors.append(f"{field} is invalid")
    if registry["permission_enforcement"] != {
        "scope": "repository_policy_and_command_preflight",
        "not_a_sandbox": True,
        "platform_tools_may_be_broader": True,
    }:
        errors.append("permission_enforcement must state the repository-preflight, non-sandbox boundary")
    errors.extend(validate_task_execution_control(registry.get("task_execution_control")))
    expected_external_access = {
        "public_web_read": {"class": "read_only_evidence_acquisition",
            "allowed_sources": "opened_public_urls_only", "requirements": ["opened_content", "citation", "capture_provenance"],
            "platform_availability_separate": True},
        "private_external_contact": {"class": "unsupported_effect",
            "status": "declared_fail_closed_unsupported", "includes": ["authenticated_session", "message_or_transaction", "broker_private_effect"]},
    }
    if registry.get("external_access_classes") != expected_external_access:
        errors.append(
            "external_access_classes must separate public web read from private effects"
        )

    roles = registry["roles"]
    expected = {
        "A3", "AI-E", "BB", "CC", "E1", "E1a", "E2", "E3", "E4", "E5",
        "FA", "IB", "MIT", "OPS", "PA", "PM", "QA", "QC", "R4", "TW",
    }
    if set(roles) != expected:
        errors.append(f"role roster mismatch: expected={sorted(expected)} actual={sorted(roles)}")
    expected_generated_views = {
        ".claude/agents/<NATIVE_AGENT>.md",
        ".codex/agents/<ROLE>.md",
        ".codex/agents/<NATIVE_AGENT>.toml",
        "docs/CCAgentWorkSpace/<ROLE>/profile.md",
        ".codex/agents/INDEX.md",
        ".codex/skills/INDEX.md",
    }
    if set(registry.get("generated_views", [])) != expected_generated_views:
        errors.append("generated_views inventory does not match renderer-owned surfaces")
    expected_native_adapters = {
        "PA": [
            {"name": "PA-design-writer", "node_class": "work", "permission": "design_writer"},
            {"name": "PA-investigator", "node_class": "verification", "permission": "read_only"},
        ],
        "E4": [
            {"name": "E4-writer", "node_class": "work", "permission": "test_writer"},
            {"name": "E4-verifier", "node_class": "verification", "permission": "read_only"},
        ],
    }
    if registry.get("native_agent_adapters") != expected_native_adapters:
        errors.append("native_agent_adapters must split PA/E4 writer and verifier identities")

    permissions = registry["permission_profiles"]
    capabilities = registry["capability_packs"]
    context_packs = registry["context_packs"]
    source_specs_by_name: dict[str, Any] = {}
    for pack_name, source_specs in context_packs.items():
        if not isinstance(source_specs, list) or not source_specs:
            errors.append(f"{pack_name}: context pack must contain sources")
            continue
        for source_spec in source_specs:
            for error in context_source_spec_errors(source_spec):
                errors.append(f"{pack_name}: {error}")
            name = source_name(source_spec)
            if name in source_specs_by_name and source_specs_by_name[name] != source_spec:
                errors.append(f"{name}: conflicting Context source specs")
            source_specs_by_name[name] = source_spec
    for role_id, spec in roles.items():
        missing = ROLE_REQUIRED - set(spec)
        if missing:
            errors.append(f"{role_id}: missing fields {sorted(missing)}")
            continue
        if spec["execution_mode"] not in VALID_EXECUTION_MODES:
            errors.append(f"{role_id}: invalid execution_mode {spec['execution_mode']}")
        if spec["codex_type"] not in VALID_CODEX_TYPES:
            errors.append(f"{role_id}: invalid codex_type {spec['codex_type']}")
        if spec["permission"] not in permissions:
            errors.append(f"{role_id}: unknown permission {spec['permission']}")
        for capability in spec["capabilities"]:
            if capability not in capabilities:
                errors.append(f"{role_id}: unknown capability {capability}")
        for context_pack in spec["context_packs"]:
            if context_pack not in context_packs:
                errors.append(f"{role_id}: unknown context pack {context_pack}")
        for skill in spec["skills"]:
            if not (root / ".claude" / "skills" / skill / "SKILL.md").is_file():
                errors.append(f"{role_id}: missing skill file {skill}")
        if not all(spec[field] for field in ("activation", "skip_when", "owns", "refuses", "output", "judgment_rules")):
            errors.append(f"{role_id}: role Interface fields must be non-empty")
        if role_id == "PM":
            if spec["output"] != "closure_packet_v1" or "payload_kind" in spec:
                errors.append("PM must own closure_packet_v1 without a delegated payload_kind")
        elif spec["output"] != "role_fragment_v1" or not spec.get("payload_kind"):
            errors.append(f"{role_id}: delegated roles must output role_fragment_v1 with payload_kind")
        persona_text = " ".join(_iter_text({"summary": spec["summary"], "lens": spec["lens"], "rules": spec["judgment_rules"]}))
        if FICTIONAL_PERSONA_RE.search(persona_text):
            errors.append(f"{role_id}: fictional credential/persona text is forbidden")

    for skill, binding in registry["on_demand_skills"].items():
        if not (root / ".claude" / "skills" / skill / "SKILL.md").is_file():
            errors.append(f"on-demand skill is missing: {skill}")
        if not binding.get("owners") or any(owner not in roles for owner in binding.get("owners", [])):
            errors.append(f"on-demand skill has invalid owners: {skill}")

    for role_id in REVIEW_ROLES:
        spec = roles.get(role_id, {})
        if spec.get("permission") != "read_only":
            errors.append(f"{role_id}: reviewer must use read_only permission")
        write_tools = {"Edit", "Write", "NotebookEdit"} & set(spec.get("tools", []))
        if write_tools:
            errors.append(f"{role_id}: reviewer exposes write tools {sorted(write_tools)}")
        if not {"Edit", "Write"}.issubset(set(spec.get("disallowed_tools", []))):
            errors.append(f"{role_id}: reviewer must explicitly disallow Edit and Write")

    for role_id, implementation in (("BB", "bybit"), ("IB", "ibkr")):
        adapter = roles.get(role_id, {}).get("adapter", {})
        if adapter != {"interface": "broker_compatibility_v1", "implementation": implementation}:
            errors.append(f"{role_id}: invalid broker adapter declaration")
    if roles.get("OPS", {}).get("permission") != "read_only":
        errors.append("OPS must be read_only")
    if not {"apply/restart", "PG write"}.issubset(set(roles.get("OPS", {}).get("refuses", []))):
        errors.append("OPS must refuse apply/restart and PG write")

    full_audit = registry["workflow_contracts"].get("full_audit_v3", {})
    expected_axes = ["CC", "FA", "E2", "E3", "BB", "IB", "OPS", "QC", "MIT", "AI-E", "E5", "A3", "R4"]
    if full_audit != {
        "controller_node_id": "ai_economics_review",
        "controller_role": "AI-E",
        "axes": expected_axes,
    }:
        errors.append("workflow_contracts.full_audit_v3 is invalid")
    if registry["workflow_contracts"].get("profit_diagnosis_v1") != {
        "controller_node_id": "profit_control",
        "controller_role": "AI-E",
        "evidence_axes": ["OPS", "MIT", "AI-E"],
        "probe_axes": ["QC", "BB", "IB", "MIT", "AI-E", "EXT"],
    }:
        errors.append("workflow_contracts.profit_diagnosis_v1 is invalid")
    errors.extend(registry_contract_errors(registry, root))

    for adapter_id, adapter in registry["effect_adapters"].items():
        if not adapter.get("authority") or not adapter.get("invariant"):
            errors.append(f"{adapter_id}: effect Adapter requires authority and invariant")
        if adapter_id == "broker_probe_adapter_v1" and adapter.get("status") != "declared_fail_closed_unsupported":
            errors.append("broker_probe_adapter_v1 must remain declared fail-closed until implemented")
        if adapter_id == "deploy_adapter_v1" and adapter.get("status") != (
            "declared_apply_disabled_until_recovery_controls_bound"
        ):
            errors.append(
                "deploy_adapter_v1 must remain apply-disabled until recovery controls are bound"
            )
        paths = list(adapter.get("implementation_paths", [])) + list(adapter.get("component_paths", []))
        if adapter.get("intent_schema_path"):
            paths.append(adapter["intent_schema_path"])
        if adapter.get("receipt_schema_path"):
            paths.append(adapter["receipt_schema_path"])
        for implementation in adapter.get("implementations", {}).values():
            if not implementation.get("status"):
                errors.append(f"{adapter_id}: implementation status is required")
            paths.extend(implementation.get("paths", []))
        if not paths and adapter_id != "terminal_receipt_sink_v1":
            errors.append(f"{adapter_id}: effect Adapter has no implementation path")
        for path in paths:
            if Path(path).is_absolute() or not (root / path).is_file():
                errors.append(f"{adapter_id}: missing repository implementation path {path}")

    errors.extend(registry_budget_errors(registry["budget_envelopes"]))
    errors.extend(registry_capability_errors(registry))
    return errors


def _bullets(values: Iterable[str]) -> str:
    return "\n".join(f"- {value}" for value in values)


def _render_claude(
    role_id: str, spec: dict[str, Any], adapter: dict[str, str],
    skills: list[tuple[str, str]],
) -> str:
    native_name = adapter["name"]
    permission = adapter["permission"]
    read_only = adapter["node_class"] == "verification"
    tools = list(spec["tools"])
    disallowed_tools = list(spec["disallowed_tools"])
    owns = list(spec["owns"])
    refuses = list(spec["refuses"])
    description = spec["summary"]
    if read_only:
        write_tools = {"Edit", "Write", "NotebookEdit", "TodoWrite"}
        tools = [tool for tool in tools if tool not in write_tools]
        disallowed_tools = sorted(set(disallowed_tools) | write_tools)
        if role_id == "E4":
            description = (
                "Read-only E4 verifier for test gaps, admitted regression runs, "
                "and independent test-evidence review."
            )
            owns = ["test-gap analysis", "regression selection",
                    "independent verification of test evidence"]
            refuses = [*refuses, "test or source implementation"]
        elif role_id == "PA":
            description = (
                "Read-only PA investigator for architecture, interface invariants, "
                "and minimum coherent change analysis."
            )
    disallowed = ""
    if disallowed_tools:
        disallowed = "disallowedTools: " + ", ".join(disallowed_tools) + "\n"
    bash_policy = ""
    if read_only and "Bash" in tools:
        bash_policy = (
            " Run verification only through `python3 helper_scripts/maintenance_scripts/"
            f"agent_governance.py capture-command --native-agent {native_name} "
            "--node-id <admitted-node-id> --context-artifact @<context.json> -- <argv...>`. "
            "It preflights and executes once with shell=false; never run the argv separately."
        )
    web_boundary = (
        " Web tools are admitted only for a task_contract with public_web_read and "
        "an owned evidence-acquisition node. Only opened public URLs preserved as "
        "external_evidence_capture_v1 with citation/provenance can support a claim; "
        "platform availability grants no private/authenticated contact or effect authority."
        if {"WebSearch", "WebFetch"}.intersection(tools)
        else " This identity has no admitted public-web tool."
    )
    completion = (
        "Integrate immutable role fragments, validate them against `closure_packet_v1`, and return the single final closure packet. Preserve dissent; do not append role memory or write per-role reports. Use the deterministic Report Sink only for an explicitly durable projection."
        if role_id == "PM"
        else f"Return an immutable `{spec['output']}` with payload_kind `{spec['payload_kind']}` and the admitted `task_contract_digest` for PM to merge into `closure_packet_v1`. Do not append role memory or write a per-role report by default. Persist only through the deterministic Report Sink when PM declares a durable closure projection."
    )
    return f"""---
name: {native_name}
description: {description}
tools: {', '.join(tools)}
{disallowed}model: inherit
color: {spec.get('color', 'blue')}
---

{GENERATED_NOTICE}

# {native_name} — Registry role {role_id} / {adapter['node_class']}

Registry authority: `.codex/agent_registry_v1.json`.

## Decision lens

{spec['lens']}

## Activate / skip

Activate when:

{_bullets(spec['activation'])}

Skip when:

{_bullets(spec['skip_when'])}

## Ownership boundary

Owns:

{_bullets(owns)}

Refuses:

{_bullets(refuses)}

Permission profile: `{permission}`. Source/runtime effects outside that profile are forbidden even when a shell could technically perform them.{web_boundary}{bash_policy}

## Context

Consume the PM-supplied task capsule first. If it is absent or incomplete, run the Context Interface in `helper_scripts/maintenance_scripts/agent_governance.py` and expand only the declared packs: {', '.join(f'`{pack}`' for pack in spec['context_packs'])}. Role memory and old reports are on-demand history, never universal preload.

Discoverable skills are on-demand only: {'; '.join(f'`{skill}` at `.claude/skills/{skill}/SKILL.md` when {activation}' for skill, activation in skills) or 'none'}. Read a complete `SKILL.md` only when its Registry activation matches this task; never preload it.

## Judgment rules

{_bullets(spec['judgment_rules'])}

## Completion

{completion}
"""


def _render_codex(
    role_id: str, spec: dict[str, Any], adapters: list[dict[str, str]],
    skills: list[tuple[str, str]],
) -> str:
    skill_lines = [f"- `{skill}` -> `.claude/skills/{skill}/SKILL.md` when {activation}" for skill, activation in skills]
    skills = "\n".join(skill_lines) if skill_lines else "- none; use the registry charter"
    adapter = spec.get("adapter")
    adapter_line = ""
    if adapter:
        adapter_line = f"\nBroker Adapter: `{adapter['interface']}::{adapter['implementation']}`\n"
    bash_policy = ""
    if spec["permission"] == "read_only" and "Bash" in spec["tools"]:
        bash_policy = "\n- Execute verification only through the Context-bound `capture-command` Adapter; do not preflight and then run a second shell command."
    claude_adapters = ", ".join(
        f"`.claude/agents/{adapter['name']}.md`" for adapter in adapters)
    return f"""{GENERATED_NOTICE}

# {role_id}

Registry authority: `.codex/agent_registry_v1.json`
Generated Claude Adapter(s): {claude_adapters}
Codex runtime type: `{spec['codex_type']}`
Execution mode: `{spec['execution_mode']}`
Permission: `{spec['permission']}`{adapter_line}

## Lens

{spec['lens']}

## Activation

{_bullets(spec['activation'])}

## Boundary

Owns:

{_bullets(spec['owns'])}

Refuses:

{_bullets(spec['refuses'])}

## Capability packs

{_bullets(spec['capabilities'])}

## Skills

{skills}

## Context and output

- Context packs: {', '.join(f'`{pack}`' for pack in spec['context_packs'])}
- Output fragment: `{spec['output']}`
{f"- Payload kind: `{spec['payload_kind']}`" if role_id != 'PM' else '- Final packet owner: `closure_packet_v1`'}
- No universal role-memory/report preload. Expand source evidence on demand.
- No automatic memory/report write; PM owns the single task closure.{bash_policy}
"""


def _native_adapters(
    registry: dict[str, Any], role_id: str, spec: dict[str, Any]
) -> list[dict[str, str]]:
    configured = registry["native_agent_adapters"].get(role_id)
    if configured:
        return configured
    node_class = "verification" if spec["permission"] == "read_only" else "work"
    return [{
        "name": role_id,
        "node_class": node_class,
        "permission": "read_only" if node_class == "verification" else spec["permission"],
    }]


def native_agent_binding(
    role_id: str, node_class: str, registry: dict[str, Any] | None = None,
) -> dict[str, str]:
    """Resolve one Registry-authoritative pre-spawn native identity."""

    registry = registry or load_registry()
    spec = registry.get("roles", {}).get(role_id)
    if not isinstance(spec, dict) or role_id == "PM":
        raise ValueError(f"role {role_id!r} is not a delegated native role")
    if node_class not in {"work", "verification"}:
        raise ValueError(f"node_class {node_class!r} is invalid")
    permission = spec["permission"] if node_class == "work" else "read_only"
    for adapter in _native_adapters(registry, role_id, spec):
        if (
            adapter["node_class"] == node_class
            and adapter["permission"] == permission
        ):
            return {
                "native_agent": adapter["name"],
                "node_class": node_class,
                "permission": permission,
            }
    raise ValueError(
        f"role {role_id} has no native {node_class}/{permission} adapter"
    )


def native_agent_contract(
    native_agent: str, registry: dict[str, Any] | None = None,
) -> dict[str, str]:
    """Resolve an exact native identity without trusting caller-supplied role facts."""

    registry = registry or load_registry()
    matches: list[dict[str, str]] = []
    for role_id, spec in registry.get("roles", {}).items():
        for adapter in _native_adapters(registry, role_id, spec):
            if adapter.get("name") == native_agent:
                matches.append(dict(
                    native_agent=native_agent, role_id=role_id,
                    node_class=adapter["node_class"], permission=adapter["permission"],
                ))
    if len(matches) != 1:
        reason = "unknown" if not matches else "ambiguous"
        raise ValueError(f"{reason} native agent {native_agent!r}")
    return matches[0]


def _render_native_agent(
    role_id: str, spec: dict[str, Any], adapter: dict[str, str],
    skills: list[tuple[str, str]],
) -> str:
    node_class = adapter["node_class"]
    permission = adapter["permission"]
    read_only = node_class == "verification"
    owns = spec["owns"]
    refuses = spec["refuses"]
    if role_id == "E4" and read_only:
        owns = [
            "test-gap analysis",
            "regression selection",
            "independent verification of test evidence",
        ]
        refuses = [*refuses, "test or source implementation"]
    boundary = (
        "Remain read-only even when the parent session has broader access. Do not edit, "
        "write reports/memory, or mutate git. A read-only sandbox is a filesystem "
        "boundary, not effect authority."
        if read_only
        else f"Write only task-owned workspace files allowed by `{permission}`. Never expand "
        "scope or approve your own change."
    )
    web_capable = bool({"WebSearch", "WebFetch"}.intersection(spec["tools"]))
    if web_capable:
        effect_boundary = (
            "Web tools require public_web_read in the task_contract and an owned "
            "evidence-acquisition node. Only opened public URLs preserved as "
            "external_evidence_capture_v1 with citation/provenance support claims; "
            "tool availability grants no private/authenticated effect authority."
        )
        if role_id in {"BB", "IB"}:
            effect_boundary += (
                " Broker-policy freshness requires opening the current official source; "
                "search snippets and training memory are not evidence."
            )
    else:
        effect_boundary = (
            "This identity has no admitted public-web tool. Service mutation, "
            "private/authenticated external contact or effect, and private broker "
            "effects remain forbidden regardless of sandbox mode."
        )
    bash_preflight = (
        "\n- Run an intended verification argv only through `python3 helper_scripts/"
        "maintenance_scripts/agent_governance.py capture-command "
        f"--native-agent {adapter['name']} --node-id <admitted-node-id> "
        "--context-artifact @<context.json> -- <argv...>`. The Adapter derives scope, "
        "preflights, and executes with shell=false; never run the argv separately. Its "
        "effect boundary is repository_policy_only, not host no-contact attestation."
        if read_only else ""
    )
    completion = (
        "Return the single validated `closure_packet_v1` and preserve independent dissent."
        if role_id == "PM"
        else f"Return immutable `{spec['output']}` evidence with payload kind "
        f"`{spec['payload_kind']}` and the admitted task-contract digest."
    )
    skill_route = ", ".join(
        f"`${skill}` at `.agents/skills/{skill}/SKILL.md` when {activation}"
        for skill, activation in skills
    ) or "registry charter only"
    instructions = f"""Registry role `{role_id}`; native identity `{adapter['name']}`.
Registry authority: `.codex/agent_registry_v1.json`.

Decision lens:
{spec['lens']}

Activate for:
{_bullets(spec['activation'])}

Own:
{_bullets(owns)}

Refuse:
{_bullets(refuses)}

Judgment:
{_bullets(spec['judgment_rules'])}

Operating contract:
- Consume the admitted Context capsule first; expand only direct evidence and packs needed for this task.
- Optimize for the shortest durable, risk-adjusted profitable closure. Token savings count only when false closure and rework risk do not rise.
- {boundary}
- {effect_boundary}{bash_preflight}
- When the admitted task activates a repo skill, read its complete `SKILL.md`
  before acting. Discoverable skill bindings: {skill_route}. Do not preload them.
- {completion}
"""
    effort = "high"
    if role_id == "E4" and read_only:
        description = (
            "Read-only E4 verifier that reviews test gaps, runs admitted tests, "
            "and evaluates regression evidence."
        )
    elif role_id == "PA" and read_only:
        description = (
            "Read-only PA investigator for architecture, interface invariants, "
            "and minimum coherent change analysis."
        )
    else:
        description = (
            f"{spec['summary']} Native {node_class} adapter for Registry role {role_id}."
        )
    sandbox = "read-only" if read_only else "workspace-write"
    return "\n".join([
        GENERATED_TOML_NOTICE,
        f"name = {json.dumps(adapter['name'], ensure_ascii=False)}",
        f"description = {json.dumps(description, ensure_ascii=False)}",
        f"model_reasoning_effort = {json.dumps(effort)}",
        f"sandbox_mode = {json.dumps(sandbox)}",
        f"developer_instructions = {json.dumps(instructions, ensure_ascii=False)}",
        "",
    ])


def _render_profile(role_id: str, spec: dict[str, Any]) -> str:
    adapter = spec.get("adapter")
    adapter_text = ""
    if adapter:
        adapter_text = f"\n- Adapter: `{adapter['interface']}::{adapter['implementation']}`"
    payload_text = f"\n- Payload kind: `{spec['payload_kind']}`" if role_id != "PM" else ""
    return f"""{GENERATED_NOTICE}

# {role_id} Role Profile

This is a generated human-readable projection. The stable Interface is
`.codex/agent_registry_v1.json`; domain depth lives in the referenced skills.

- Execution mode: `{spec['execution_mode']}`
- Codex type: `{spec['codex_type']}`
- Permission: `{spec['permission']}`
- Output: `{spec['output']}`{payload_text}{adapter_text}

## Decision lens

{spec['lens']}

## Activate / skip

Activate:

{_bullets(spec['activation'])}

Skip:

{_bullets(spec['skip_when'])}

## Owns / refuses

Owns:

{_bullets(spec['owns'])}

Refuses:

{_bullets(spec['refuses'])}

## Judgment rules

{_bullets(spec['judgment_rules'])}

Role memory and historical reports are optional evidence sources, not startup authority. Current work state comes from `TODO.md`; hard policy comes from `CLAUDE.md` and accepted ADR/AMD sources.
"""


def _render_index(registry: dict[str, Any]) -> str:
    rows = []
    for role_id, spec in registry["roles"].items():
        adapter = spec.get("adapter", {}).get("implementation", "-")
        native_adapters = _native_adapters(registry, role_id, spec)
        native = "<br>".join(
            f"[`{item['name']}.toml`](./{item['name']}.toml)"
            for item in native_adapters
        )
        claude = "<br>".join(
            f"`{item['name']}.md`" for item in native_adapters
        )
        rows.append(
            f"| `{role_id}` | `{spec['execution_mode']}` | `{spec['codex_type']}` | "
            f"`{spec['permission']}` | {native} | {claude} | `{adapter}` |"
        )
    return f"""{GENERATED_NOTICE}

# Development Sub-Agent Index

The canonical Interface is `.codex/agent_registry_v1.json`. Role names are
capability presets over four execution modes; they are not independently
maintained personas. Native Codex TOML adapters under `.codex/agents/*.toml`
and matching Claude agents under `.claude/agents/*.md` are executable identities;
adjacent Codex Markdown and role profiles are generated human views. All are
Registry projections and must pass
`python3 helper_scripts/maintenance_scripts/agent_governance.py render --check`.

| Role | Execution mode | Codex type | Permission | Native Codex TOML | Claude agent | Broker Adapter |
|---|---|---|---|---|---|---|
{chr(10).join(rows)}

## Loading route

1. Bind a role, ownership, task shape, expected output, and risk facts.
2. Compile an adaptive context plan; mandatory user scope, acceptance, hard
   boundaries, current diff/interfaces, and fresh blockers are never truncated.
3. Read role skills and task evidence on demand. Do not universal-preload all
   role memories, reports, README, TODO, and full operating memory.
4. Return an immutable role fragment. PM produces at most one durable
   `closure_packet_v1` projection for the task.

Runtime type is an execution substrate, never a model-intelligence tier.
"""


def _render_skill_index(registry: dict[str, Any]) -> str:
    owners: dict[str, set[str]] = {}
    for role_id, spec in registry["roles"].items():
        for skill in spec["skills"]:
            owners.setdefault(skill, set()).add(role_id)
    rows: list[str] = []
    for skill, role_ids in owners.items():
        rendered_owners = ", ".join(f"`{role}`" for role in sorted(role_ids))
        rows.append(
            f"| `{skill}` | `.agents/skills/{skill}/SKILL.md` | "
            f"`.claude/skills/{skill}/SKILL.md` | {rendered_owners} | role-bound |"
        )
    for skill, spec in registry["on_demand_skills"].items():
        rendered_owners = ", ".join(f"`{role}`" for role in sorted(spec["owners"]))
        rows.append(
            f"| `{skill}` | `.agents/skills/{skill}/SKILL.md` | "
            f"`.claude/skills/{skill}/SKILL.md` | {rendered_owners} | "
            f"on-demand: {spec['activation']} |"
        )
    return f"""{GENERATED_NOTICE}

# Codex Skill Index

Skill ownership is generated from `.codex/agent_registry_v1.json`. Codex scans
the `.agents/skills` discovery adapters; each is a symlink to the canonical
`.claude/skills` corpus, so both platforms use one body without content drift.
On-demand skills are never universal preload.

| Skill | Codex discovery | Canonical source | Owners | Binding |
|---|---|---|---|---|
{chr(10).join(sorted(rows))}
"""


def render_views(registry: dict[str, Any], root: Path = REPO_ROOT) -> dict[Path, str]:
    """Project the registry into platform and human-readable Adapter views."""

    rendered: dict[Path, str] = {
        root / ".codex/agents/INDEX.md": _render_index(registry),
        root / ".codex/skills/INDEX.md": _render_skill_index(registry),
    }
    for role_id, spec in registry["roles"].items():
        adapters = _native_adapters(registry, role_id, spec)
        skill_names = sorted(set(spec["skills"]) | {
            skill for skill, binding in registry["on_demand_skills"].items()
            if role_id in binding["owners"]
        })
        skills = [(skill, registry["on_demand_skills"].get(skill, {}).get(
            "activation", "the admitted role task explicitly needs it")) for skill in skill_names]
        rendered[root / f".codex/agents/{role_id}.md"] = _render_codex(role_id, spec, adapters, skills)
        for adapter in adapters:
            rendered[root / f".claude/agents/{adapter['name']}.md"] = (
                _render_claude(role_id, spec, adapter, skills)
            )
            rendered[root / f".codex/agents/{adapter['name']}.toml"] = (
                _render_native_agent(role_id, spec, adapter, skills)
            )
        rendered[root / f"docs/CCAgentWorkSpace/{role_id}/profile.md"] = _render_profile(role_id, spec)
    return rendered


def render_all(registry: dict[str, Any], root: Path = REPO_ROOT, *, check: bool = False) -> list[str]:
    """Render views or return paths that drift from their deterministic projection."""

    drift: list[str] = []
    for path, content in render_views(registry, root).items():
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        drift.append(str(path.relative_to(root)))
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    expected = set(render_views(registry, root))
    inventory = [
        *(root / ".claude/agents").glob("*.md"),
        *(root / ".codex/agents").glob("*.md"),
        *(root / ".codex/agents").glob("*.toml"),
        *(root / "docs/CCAgentWorkSpace").glob("*/profile.md"),
    ]
    for path in sorted(set(inventory) - expected):
        drift.append(str(path.relative_to(root)))
    return drift
