"""Shared fixtures and payload builders for Stock/ETF route tests."""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Any
from unittest.mock import AsyncMock, patch

import pytest

_test_dir = os.path.dirname(os.path.abspath(__file__))
_control_api_dir = os.path.dirname(_test_dir)
if _control_api_dir not in sys.path:
    sys.path.insert(0, _control_api_dir)

from fastapi import FastAPI  # noqa: E402
from fastapi.testclient import TestClient  # noqa: E402

from app import stock_etf_routes as route_module  # noqa: E402
from app.main_legacy import AuthenticatedActor, current_actor  # noqa: E402
from app.stock_etf_routes import stock_etf_router  # noqa: E402

STATIC_DIR = Path(__file__).resolve().parents[1] / "app" / "static"


def _viewer_actor() -> AuthenticatedActor:
    return AuthenticatedActor(
        actor_id="test-viewer",
        actor_type="human",
        roles={"viewer"},
        scopes={"private_readonly"},
    )


@pytest.fixture
def client_fail_closed() -> TestClient:
    route_module._IPC_CLIENT = None
    app = FastAPI()
    app.include_router(stock_etf_router)
    app.dependency_overrides[current_actor] = _viewer_actor
    with patch.object(route_module, "_get_ipc", AsyncMock(return_value=None)):
        yield TestClient(app)


def _make_client_with_ipc(fake_ipc: Any) -> TestClient:
    route_module._IPC_CLIENT = None
    app = FastAPI()
    app.include_router(stock_etf_router)
    app.dependency_overrides[current_actor] = _viewer_actor
    patcher = patch.object(route_module, "_get_ipc", AsyncMock(return_value=fake_ipc))
    patcher.start()
    client = TestClient(app)
    client._stock_etf_patcher = patcher  # type: ignore[attr-defined]
    return client


def _valid_api_allowlist() -> dict[str, Any]:
    return {
        "contract_id": "non_bybit_api_allowlist_v1",
        "source_version": 1,
        "accepted": True,
        "blockers": [],
        "read_action_count": 10,
        "paper_write_action_count": 3,
        "denied_action_count": 10,
        "ibkr_contact_performed": False,
        "secret_content_serialized": False,
        "bybit_live_execution_protected": True,
    }


def _valid_phase0_status() -> dict[str, Any]:
    return {
        "phase": "phase0_contract_packet_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "scope": "paper_shadow_only",
        "gui_authority": "display_only",
        "phase0_status_state": "accepted_no_runtime_authority",
        "phase0_accepted": True,
        "phase0_blockers": [],
        "contract_count": 33,
        "contracts": [
            "asset_lane_taxonomy_v1",
            "broker_capability_registry_v1",
            "phase2_ibkr_external_surface_gate_v1",
            "non_bybit_api_allowlist_v1",
            "stock_etf_ibkr_readonly_probe_request_v1",
            "instrument_identity_contract_v1",
            "stock_etf_pit_universe_contract_v1",
            "stock_etf_strategy_hypothesis_contract_v1",
            "stock_etf_risk_policy_v1",
            "stock_etf_reference_data_sources_v1",
            "ibkr_api_session_topology_v1",
            "ibkr_session_attestation_v1",
            "feature_flag_secret_auth_matrix_v1",
            "lane_scoped_ipc_v1",
            "stock_etf_paper_order_request_v1",
            "stock_etf_paper_fill_import_request_v1",
            "stock_etf_shadow_signal_request_v1",
            "ibkr_paper_order_lifecycle_v1",
            "broker_lifecycle_event_log_v1",
            "audit.asset_lane_events_v1",
            "stock_etf_db_evidence_ddl_v1",
            "stock_market_data_provenance_v1",
            "broker_account_portfolio_cash_ledger_v1",
            "cost_model_version_v1",
            "benchmark_versions_v1",
            "stock_shadow_fill_model_v1",
            "stock_etf_paper_shadow_reconciliation_v1",
            "stock_etf_evidence_clock_v1",
            "gui_lane_contract_v1",
            "stock_etf_storage_capacity_v1",
            "stock_etf_kill_switch_and_disable_cleanup_runbook_v1",
            "stock_etf_release_packet_v1",
            "tiny_live_adr_eligibility_v1",
        ],
        "manifest": {
            "schema": "stock_etf_phase0_contract_packet_manifest_v1",
            "generated_at": "2026-06-29",
            "status": "ACCEPTED_PHASE0_CONTRACT_NO_RUNTIME_AUTHORITY",
            "scope": "paper_shadow_only",
            "adr": "docs/adr/0048-ibkr-stock-etf-paper-shadow-lane.md",
            "amd": "docs/governance_dev/amendments/2026-06-29--AMD-2026-06-29-01-ibkr-stock-etf-paper-shadow-lane.md",
            "contract_packet": "docs/execution_plan/specs/2026-06-29--stock_etf_cash_phase0_named_contract_packet.md",
        },
        "api_baseline": {
            "selected": "ib_gateway_tws_api",
            "host_policy": "loopback_only",
            "paper_port_default_candidate": 4002,
            "live_ports_denied": True,
            "ibkr_call_performed": False,
        },
        "global_denials": {
            "ibkr_live": True,
            "tiny_live": True,
            "margin": True,
            "short": True,
            "options": True,
            "cfd": True,
            "transfer": True,
            "account_management_writes": True,
            "python_broker_write_authority": True,
            "gui_lane_authority": True,
            "automatic_promotion": True,
        },
        "phase_unlock": {
            "phase1_type_config_schema_ipc": "ALLOWED_AFTER_THIS_PACKET_WITH_E2_E4_QA",
            "phase2_ibkr_external_contact": "BLOCKED_UNTIL_PHASE2_EXTERNAL_SURFACE_GATE_PASS",
            "phase3_evidence_clock": "BLOCKED_UNTIL_DATA_PROVENANCE_EVIDENCE_CONTRACTS_PASS",
            "phase4_gui_runtime": "BLOCKED_UNTIL_ROUTE_CACHE_AUTH_NEGATIVE_TESTS_PASS",
            "phase5_paper_shadow_online": "BLOCKED_UNTIL_RELEASE_PACKET_AND_SHAKEDOWN_PASS",
            "tiny_live_or_live": "BLOCKED_REQUIRES_FUTURE_ADR",
        },
        "phase1_runtime_started": False,
        "phase2_started": False,
        "phase3_started": False,
        "phase4_runtime_started": False,
        "phase5_started": False,
        "paper_shadow_launch_authorized": False,
        "tiny_live_or_live_authorized": False,
        "connector_runtime_started": False,
        "db_apply_performed": False,
        "evidence_clock_started": False,
        "scorecard_writer_started": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
    }


def _valid_lane_status() -> dict[str, Any]:
    return {
        "phase": "phase2_precontact_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "default_asset_lane": "crypto_perp",
        "flags": {
            "stock_etf_lane_enabled": True,
            "ibkr_readonly_enabled": True,
            "ibkr_paper_enabled": False,
            "asset_lane_default": "crypto_perp",
            "stock_etf_shadow_only": True,
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
        },
        "ibkr_live_enabled": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
    }


def _valid_data_foundation_status() -> dict[str, Any]:
    return {
        "phase": "phase2_data_foundation_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "environment": "paper",
        "data_foundation_status_state": "blocked",
        "phase2_started": False,
        "phase3_started": False,
        "contract_details_request_started": False,
        "reference_data_collection_started": False,
        "collector_started": False,
        "market_data_ingestion_started": False,
        "connector_runtime_started": False,
        "db_apply_performed": False,
        "evidence_clock_started": False,
        "scorecard_writer_started": False,
        "instrument_identity": {
            "expected_contract_id": "instrument_identity_contract_v1",
            "contract_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": ["contract_id_mismatch", "source_version_mismatch"],
            "symbol": "",
            "instrument_kind": "stock",
            "listing_venue": "unknown_denied",
            "primary_exchange": "unknown_denied",
            "currency": "unknown_denied",
            "tradability_status": "unknown_denied",
            "priips_kid_status": "unknown_denied",
            "fractional_policy_recorded": False,
            "point_in_time_asof_ms": 0,
            "market_calendar_id_present": False,
            "market_calendar_hash_present": False,
            "broker_contract_details_hash_present": False,
            "instrument_identity_hash_present": False,
            "corporate_action_adjustment_version_hash_present": False,
            "source_artifact_hash_present": False,
            "bybit_live_execution_unchanged": True,
            "ibkr_live_denied": True,
            "margin_short_denied": True,
            "options_cfd_denied": True,
            "ibkr_contact_performed": False,
            "secret_content_serialized": False,
        },
        "reference_data_sources": {
            "expected_contract_id": "stock_etf_reference_data_sources_v1",
            "contract_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": ["contract_id_mismatch", "source_version_mismatch"],
            "environment": "paper",
            "frozen_for_evidence_clock": False,
            "corporate_action_source_name": "",
            "corporate_action_asof_ms": 0,
            "corporate_action_raw_hash_present": False,
            "corporate_action_adjustment_version_hash_present": False,
            "corporate_action_policy_hash_present": False,
            "dividend_treatment_hash_present": False,
            "fx_rate_source_name": "",
            "fx_rate_asof_ms": 0,
            "base_currency": "unknown_denied",
            "quote_currency": "unknown_denied",
            "fx_rate_snapshot_hash_present": False,
            "fx_drag_model_hash_present": False,
            "fee_schedule_source_name": "",
            "fee_schedule_asof_ms": 0,
            "commission_schedule_hash_present": False,
            "exchange_regulatory_fee_hash_present": False,
            "tax_ftt_placeholder_hash_present": False,
            "withholding_tax_treatment_hash_present": False,
            "source_artifact_hash_present": False,
            "bybit_live_execution_unchanged": True,
            "ibkr_contact_performed": False,
            "connector_runtime_started": False,
            "secret_content_serialized": False,
            "live_or_tiny_live_authorized": False,
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
            "secret_slot_touched": False,
            "order_routed": False,
        },
        "ibkr_live_enabled": False,
        "stock_live_disabled": True,
        "paper_order_entry_visible": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
    }


def _valid_policy_status() -> dict[str, Any]:
    return {
        "phase": "phase2_policy_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "environment": "paper",
        "policy_status_state": "blocked",
        "phase2_started": False,
        "phase3_started": False,
        "risk_runtime_started": False,
        "paper_order_rehearsal_started": False,
        "paper_order_submitted": False,
        "connector_runtime_started": False,
        "db_apply_performed": False,
        "evidence_clock_started": False,
        "scorecard_writer_started": False,
        "risk_policy": {
            "expected_contract_id": "stock_etf_risk_policy_v1",
            "contract_id": "",
            "source_version": 0,
            "config_version": 0,
            "accepted": False,
            "blockers": ["contract_id_mismatch", "source_version_mismatch"],
            "environment": "paper",
            "enabled": False,
            "shadow_only": True,
            "max_order_notional_usd": 0,
            "max_position_notional_usd": 0,
            "max_daily_notional_usd": 0,
            "max_open_orders": 0,
            "max_open_positions": 0,
            "allow_fractional_shares": False,
            "allow_margin": False,
            "allow_short": False,
            "allow_options": False,
            "allow_cfd": False,
            "allow_transfer": False,
            "allow_live": False,
            "allowed_kind_count": 0,
            "denied_kind_count": 0,
            "requires_frozen_universe_hash": False,
            "requires_instrument_identity_hash": False,
            "requires_market_session": False,
            "cost_model_required_before_shadow_fill": False,
            "cost_model_required_before_scorecard": False,
            "commission_schedule_required": False,
            "spread_estimate_required": False,
            "slippage_estimate_required": False,
            "fx_drag_required": False,
            "conservative_fill_penalty_required": False,
            "rust_authority_required": False,
            "session_attestation_required": False,
            "decision_lease_required": False,
            "guardian_required": False,
            "idempotency_key_required": False,
            "broker_reconciliation_required": False,
            "bybit_live_execution_unchanged": True,
            "ibkr_contact_performed": False,
            "connector_runtime_started": False,
            "secret_content_serialized": False,
        },
        "broker_capability_registry": {
            "expected_registry_id": "broker_capability_registry_v1",
            "registry_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": ["registry_id_mismatch", "source_version_mismatch"],
            "operation_count": 0,
            "required_audit_field_count": 0,
            "read_operation_count": 0,
            "lane_scoped_ipc_contract_id": "lane_scoped_ipc_v1",
            "readonly_probe_request_contract_id": (
                "stock_etf_ibkr_readonly_probe_request_v1"
            ),
            "read_rows_require_lane_scoped_ipc": False,
            "read_rows_require_readonly_probe_request": False,
            "paper_operation_count": 0,
            "denied_operation_count": 0,
            "bybit_live_execution_unchanged": True,
            "python_broker_write_authority_denied": True,
            "ibkr_live_denied": True,
            "cfd_margin_reserved_denied": True,
            "first_ibkr_contact_performed": False,
            "secret_content_serialized": False,
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
            "secret_slot_touched": False,
            "order_routed": False,
        },
        "ibkr_live_enabled": False,
        "stock_live_disabled": True,
        "paper_order_entry_visible": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
    }


def _valid_authorization_status() -> dict[str, Any]:
    return {
        "phase": "phase2_authorization_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "environment": "paper",
        "authorization_status_state": "blocked",
        "phase2_started": False,
        "phase3_started": False,
        "risk_runtime_started": False,
        "paper_order_rehearsal_started": False,
        "paper_order_submitted": False,
        "connector_runtime_started": False,
        "db_apply_performed": False,
        "evidence_clock_started": False,
        "scorecard_writer_started": False,
        "paper_order_authority_present": False,
        "scoped_authorization_present": False,
        "decision_lease_valid": False,
        "guardian_allows": False,
        "authorization_matrix": {
            "expected_contract_id": "feature_flag_secret_auth_matrix_v1",
            "contract_id": "",
            "source_version": 0,
            "gui_lane_state_override_denied": True,
            "server_rust_matrix_authoritative": True,
            "request_asset_lane": "stock_etf_cash",
            "request_broker": "ibkr",
            "request_environment": "paper",
            "request_instrument_kind": "stock",
            "request_operation": "paper_order_submit",
            "request_allowed": False,
            "effective_authority_scope": "denied",
            "blockers": ["contract_id_mismatch", "source_version_mismatch"],
        },
        "feature_flags": {
            "stock_etf_lane_enabled": False,
            "ibkr_readonly_enabled": False,
            "ibkr_paper_enabled": False,
            "asset_lane_default": "crypto_perp",
            "stock_etf_shadow_only": True,
        },
        "secret_slot_contract": {
            "expected_contract_id": "ibkr_secret_slot_contract_v1",
            "contract_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": ["contract_id_mismatch", "source_version_mismatch"],
            "contract_present": False,
            "readonly_slot_posture": "unknown",
            "paper_slot_posture": "unknown",
            "live_slot_posture": "unknown",
            "owner_only_permissions": False,
            "env_var_credential_fallback_denied": False,
            "live_secret_absent_or_empty": False,
            "secret_slot_fingerprint_present": False,
            "account_fingerprint_hash_present": False,
            "secret_content_serialized": False,
            "account_id_serialized": False,
        },
        "phase2_gate_artifact": {
            "expected_contract_id": "phase2_ibkr_external_surface_gate_v1",
            "contract_id": "",
            "source_version": 0,
            "ibkr_contact_allowed": False,
            "blockers": ["contract_id_mismatch", "source_version_mismatch"],
            "artifact_id_present": False,
            "sealed": False,
            "raw_artifact_hash_present": False,
            "redacted_summary_hash_present": False,
        },
        "session_attestation": {
            "expected_contract_id": "ibkr_session_attestation_v1",
            "contract_id": "",
            "source_version": 0,
            "status": "BLOCKED",
            "attestation_accepted": False,
            "blockers": ["contract_id_mismatch", "source_version_mismatch"],
            "environment": "read_only",
            "account_fingerprint_present": False,
            "account_fingerprint_is_live": False,
            "secret_slot_fingerprint_present": False,
            "api_server_version_present": False,
            "raw_artifact_hash_present": False,
        },
        "authorization_envelope": {
            "asset_lane": "stock_etf_cash",
            "broker": "ibkr",
            "environment": "paper",
            "permission_scope": "denied",
            "secret_slot_fingerprint_present": False,
            "account_fingerprint_hash_present": False,
            "risk_config_hash_present": False,
            "expires_at_ms": 0,
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
            "secret_slot_touched": False,
            "order_routed": False,
        },
        "ibkr_live_enabled": False,
        "stock_live_disabled": True,
        "paper_order_entry_visible": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
    }


def _valid_evidence_status() -> dict[str, Any]:
    return {
        "phase": "phase3_evidence_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "environment": "paper",
        "evidence_status_state": "blocked",
        "phase3_started": False,
        "market_data_provenance": {
            "expected_contract_id": "stock_market_data_provenance_v1",
            "contract_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": ["market_data_provenance_contract_id_mismatch"],
            "ibkr_contact_performed": False,
            "connector_runtime_started": False,
            "secret_content_serialized": False,
            "live_or_tiny_live_authorized": False,
        },
        "evidence_clock": {
            "expected_contract_id": "stock_etf_evidence_clock_v1",
            "contract_id": "",
            "source_version": 0,
            "status": "NOT_STARTED",
            "accepted": False,
            "blockers": ["evidence_clock_contract_id_mismatch"],
            "checker_contacted_ibkr": False,
            "checker_started_connector_runtime": False,
            "checker_started_evidence_clock": False,
            "checker_wrote_scorecard": False,
            "checker_applied_db": False,
            "secret_content_serialized": False,
            "live_or_tiny_live_authorized": False,
            "ibkr_readonly_paper_connector_green_5d": False,
            "shadow_collector_green_5d": False,
        },
        "frozen_inputs": {
            "accepted": False,
            "blockers": ["frozen_inputs_contract_id_mismatch"],
            "universe_hash_present": False,
            "benchmark_hash_present": False,
            "cost_model_hash_present": False,
            "strategy_hypothesis_hash_present": False,
            "reference_data_sources_contract_hash_present": False,
            "paper_shadow_divergence_threshold_hash_present": False,
            "gui_evidence_view_available": False,
            "daily_scorecard_regeneration_passed": False,
        },
        "dq_manifest": {
            "shape_accepted": False,
            "shape_blockers": ["trading_day_missing"],
            "passes_day_quality": False,
            "trading_day": "",
            "calendar_aware_coverage_bps": 0,
            "symbol_completeness_bps": 0,
            "latency_dq_passed": False,
            "market_data_provenance_accepted": False,
            "scorecard_regeneration_passed": False,
        },
        "scorecard": {
            "writer_started": False,
            "db_apply_performed": False,
            "daily_scorecard_regeneration_passed": False,
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
            "secret_slot_touched": False,
            "order_routed": False,
        },
        "ibkr_live_enabled": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
    }


def _valid_account_status() -> dict[str, Any]:
    return {
        "phase": "phase2_account_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "environment": "paper_readonly",
        "account_status_state": "blocked",
        "phase2_started": False,
        "readonly_account_snapshot_started": False,
        "paper_account_snapshot_started": False,
        "account_snapshot_present": False,
        "portfolio_positions_snapshot_present": False,
        "cash_ledger_present": False,
        "paper_account_attestation_present": False,
        "session_attestation_present": False,
        "connector_runtime_started": False,
        "gateway_socket_open": False,
        "account_snapshot": {
            "expected_contract_id": "broker_account_portfolio_cash_ledger_v1",
            "contract_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": [
                "contract_id_mismatch",
                "source_version_mismatch",
                "wrong_asset_lane",
            ],
            "account_fingerprint_hash_present": False,
            "account_snapshot_hash_present": False,
            "portfolio_positions_hash_present": False,
            "currency": "",
            "cash_balance_minor_units": 0,
            "buying_power_minor_units": 0,
            "as_of_ms": 0,
            "source_report_hash_present": False,
        },
        "session_attestation": {
            "expected_contract_id": "ibkr_session_attestation_v1",
            "contract_id": "",
            "source_version": 0,
            "status": "BLOCKED",
            "accepted": False,
            "blockers": [
                "contract_id_mismatch",
                "source_version_mismatch",
                "status_blocked",
            ],
            "account_fingerprint_present": False,
            "account_fingerprint_is_live": False,
            "environment": "read_only",
            "host": "",
            "port": 0,
            "process_identity_present": False,
            "gateway_mode": "unknown",
            "secret_slot_fingerprint_present": False,
            "secret_slot_mode": "unknown",
            "secret_world_readable": False,
            "live_secret_absent_or_empty": False,
            "env_var_credential_fallback_used": False,
            "api_server_version_present": False,
            "attested_at_ms": 0,
            "expires_at_ms": 0,
            "raw_artifact_hash_present": False,
        },
        "paper_attestation_policy": {
            "expected_contract_id": "ibkr_paper_attestation_v1",
            "contract_id": "ibkr_paper_attestation_v1",
            "source_version": 1,
            "accepted": True,
            "blockers": [],
            "external_surface_gate_required": True,
            "session_attestation_required": True,
            "rust_lane_scoped_ipc_required": True,
            "decision_lease_required": True,
            "guardian_required": True,
            "paper_environment_only": True,
            "live_account_fingerprint_denied": True,
            "margin_short_options_cfd_denied": True,
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
            "secret_slot_touched": False,
            "order_routed": False,
        },
        "ibkr_live_enabled": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
        "db_apply_performed": False,
    }


def _valid_universe_status() -> dict[str, Any]:
    return {
        "phase": "phase3_universe_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "environment": "paper",
        "universe_status_state": "blocked",
        "phase3_started": False,
        "universe": {
            "expected_contract_id": "stock_etf_pit_universe_contract_v1",
            "contract_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": ["contract_id_mismatch", "source_version_mismatch"],
            "universe_id": "",
            "universe_version": "",
            "universe_hash_present": False,
            "point_in_time_asof_ms": 0,
            "effective_from_ms": 0,
            "effective_to_ms": 0,
            "constituent_count": 0,
            "max_constituents": 0,
            "sample_constituents": [],
            "frozen_for_evidence_clock": False,
            "survivorship_bias_controls_present": False,
            "bybit_live_execution_unchanged": True,
            "ibkr_live_denied": True,
            "ibkr_contact_performed": False,
            "secret_content_serialized": False,
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
            "secret_slot_touched": False,
            "order_routed": False,
        },
        "collector_started": False,
        "market_data_ingestion_started": False,
        "db_apply_performed": False,
        "ibkr_live_enabled": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
    }


def _valid_shadow_status() -> dict[str, Any]:
    return {
        "phase": "phase3_shadow_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "environment": "shadow",
        "shadow_status_state": "blocked",
        "phase3_started": False,
        "shadow_fill_model": {
            "expected_contract_id": "stock_shadow_fill_model_v1",
            "contract_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": ["contract_id_mismatch", "source_version_mismatch"],
            "signal_id": "",
            "side": "unknown",
            "intended_notional_minor_units": 0,
            "market_session_id": "",
            "quote_or_bar_source_hash_present": False,
            "conservative_fill_price_micros": 0,
            "spread_bps": 0,
            "slippage_bps": 0,
            "cost_bps": 0,
            "rejection_reason": "",
            "synthetic_shadow": False,
            "broker_paper_fill_linked": False,
            "live_fill_linked": False,
        },
        "strategy_hypothesis": {
            "expected_contract_id": "stock_etf_strategy_hypothesis_contract_v1",
            "contract_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": ["contract_id_mismatch", "source_version_mismatch"],
            "hypothesis_id": "",
            "hypothesis_version": "",
            "strategy_family": "unknown_denied",
            "primary_timeframe": "unknown_denied",
            "instrument_scope": "unknown_denied",
            "paper_shadow_only": True,
            "profitability_claimed": False,
            "live_or_tiny_live_authority_claimed": False,
            "bybit_live_execution_unchanged": True,
            "ibkr_live_denied": True,
            "ibkr_contact_performed": False,
            "secret_content_serialized": False,
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
            "secret_slot_touched": False,
            "order_routed": False,
        },
        "shadow_collector_started": False,
        "shadow_signal_emitted": False,
        "shadow_fill_generated": False,
        "scorecard_writer_started": False,
        "db_apply_performed": False,
        "ibkr_live_enabled": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
    }


def _valid_paper_status() -> dict[str, Any]:
    return {
        "phase": "phase2_paper_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "environment": "paper",
        "paper_status_state": "blocked",
        "phase2_started": False,
        "paper_lifecycle_started": False,
        "paper_order_submitted": False,
        "paper_fill_imported": False,
        "paper_reconciliation_started": False,
        "paper_account_snapshot_present": False,
        "broker_paper_attestation_present": False,
        "lifecycle_event": {
            "expected_lifecycle_contract_id": "ibkr_paper_order_lifecycle_v1",
            "lifecycle_contract_id": "",
            "expected_event_log_contract_id": "broker_lifecycle_event_log_v1",
            "event_log_contract_id": "",
            "expected_request_contract_id": "stock_etf_paper_order_request_v1",
            "request_contract_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": [
                "lifecycle_contract_id_mismatch",
                "event_log_contract_id_mismatch",
                "source_version_mismatch",
            ],
            "operation": "paper_order_submit",
            "previous_state": "local_intent_created",
            "next_state": "local_intent_created",
            "allowed": False,
            "denial_reason": "",
            "event_id_present": False,
            "event_sequence": 0,
            "event_sequence_present": False,
            "genesis_event": False,
            "event_time_ms": 0,
            "previous_event_hash_present": False,
            "event_hash_present": False,
            "request_envelope_hash_present": False,
            "stale_state_policy": "",
            "stale_state_policy_present": False,
            "order_local_id_present": False,
            "idempotency_key_present": False,
            "broker_order_id_present": False,
            "execution_id_present": False,
            "commission_report_id_present": False,
            "reconciliation_run_id_present": False,
            "raw_artifact_hash_present": False,
            "redacted_summary_hash_present": False,
        },
        "reconstructability": {
            "append_only_event_ready": False,
            "event_hash_chain_ready": False,
            "request_envelope_linked": False,
            "stale_state_policy_present": False,
            "broker_order_id_present": False,
            "execution_id_present": False,
            "commission_report_id_present": False,
            "raw_artifact_hash_present": False,
            "redacted_summary_hash_present": False,
            "restart_recovery_required": False,
            "manual_review_required": False,
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
            "secret_slot_touched": False,
            "order_routed": False,
        },
        "ibkr_live_enabled": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
        "db_apply_performed": False,
    }


def _valid_reconciliation_status() -> dict[str, Any]:
    return {
        "phase": "phase3_reconciliation_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "environment": "paper_shadow",
        "reconciliation_status_state": "blocked",
        "phase3_started": False,
        "paper_shadow_reconciliation_started": False,
        "paper_orders_ready": False,
        "paper_fills_ready": False,
        "shadow_fills_ready": False,
        "scorecard_writer_started": False,
        "db_apply_performed": False,
        "matching": {
            "expected_lifecycle_contract_id": "ibkr_paper_order_lifecycle_v1",
            "lifecycle_contract_id": "",
            "expected_event_log_contract_id": "broker_lifecycle_event_log_v1",
            "event_log_contract_id": "",
            "expected_shadow_contract_id": "stock_shadow_fill_model_v1",
            "shadow_contract_id": "",
            "expected_reconciliation_contract_id": "stock_etf_paper_shadow_reconciliation_v1",
            "reconciliation_contract_id": "",
            "reconciliation_accepted": False,
            "reconciliation_blockers": [
                "contract_id_mismatch",
                "source_version_mismatch",
                "wrong_asset_lane",
            ],
            "lifecycle_event_accepted": False,
            "shadow_fill_model_accepted": False,
            "lifecycle_blockers": [
                "lifecycle_contract_id_mismatch",
                "event_log_contract_id_mismatch",
                "source_version_mismatch",
            ],
            "shadow_blockers": [
                "contract_id_mismatch",
                "source_version_mismatch",
                "signal_id_missing",
            ],
            "append_only_event_ready": False,
            "paper_order_id_present": False,
            "broker_order_id_present": False,
            "execution_id_present": False,
            "commission_report_id_present": False,
            "shadow_signal_id_present": False,
            "shadow_fill_price_present": False,
            "paper_shadow_link_present": False,
            "divergence_bps": 0,
            "divergence_threshold_bps": 0,
            "divergence_within_threshold": False,
            "unmatched_paper_fill_count": 0,
            "unmatched_shadow_fill_count": 0,
            "reconciliation_run_id_present": False,
            "contract_reconciliation_run_id_present": False,
            "paper_shadow_link_hash_present": False,
            "paper_fill_imported": False,
            "shadow_fill_synthetic": False,
            "raw_artifact_hash_present": False,
            "redacted_summary_hash_present": False,
            "reconciliation_writer_started": False,
            "ibkr_contact_performed": False,
            "connector_runtime_started": False,
            "secret_content_serialized": False,
            "fill_import_performed": False,
            "shadow_fill_generated": False,
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
            "secret_slot_touched": False,
            "order_routed": False,
        },
        "ibkr_live_enabled": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
    }


def _valid_scorecard_status() -> dict[str, Any]:
    return {
        "phase": "phase3_scorecard_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "environment": "paper_shadow",
        "scorecard_status_state": "blocked",
        "phase3_started": False,
        "scorecard_writer_started": False,
        "db_apply_performed": False,
        "evidence_clock_started": False,
        "paper_shadow_window_complete": False,
        "scorecard_derivation": {
            "expected_contract_id": "stock_etf_scorecard_derivation_v1",
            "contract_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": [
                "contract_id_missing",
                "source_version_mismatch",
                "wrong_asset_lane",
            ],
            "derivation_run_id_present": False,
            "strategy_id_present": False,
            "universe_version_present": False,
            "benchmark_version_present": False,
            "as_of_date_present": False,
            "scorecard_input_bundle_hash_present": False,
            "paper_shadow_reconciliation_hash_present": False,
            "scorecard_verdict_hash_present": False,
            "output_artifact_hash_present": False,
            "derived_from_atomic_facts_only": False,
            "idempotent_replay_proven": False,
            "paper_and_shadow_fills_separate": False,
            "bybit_live_execution_unchanged": False,
            "ibkr_contact_performed": False,
            "connector_runtime_started": False,
            "broker_fill_import_performed": False,
            "shadow_fill_generated": False,
            "reconciliation_writer_started": False,
            "scorecard_writer_started": False,
            "db_apply_performed": False,
            "evidence_clock_started": False,
            "secret_content_serialized": False,
            "live_or_tiny_live_authorized": False,
            "sealed": False,
        },
        "scorecard": {
            "expected_contract_id": "stock_etf_scorecard_verdict_v1",
            "contract_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": [
                "contract_id_missing",
                "source_version_mismatch",
                "wrong_asset_lane",
            ],
            "verdict_label": "insufficient_evidence",
            "scorecard_input_bundle_hash_present": False,
            "evidence_clock_manifest_hash_present": False,
            "dq_manifest_hash_present": False,
            "formula_appendix_hash_present": False,
            "statistical_preregistration_hash_present": False,
            "benchmark_version_hash_present": False,
            "cost_model_version_hash_present": False,
            "strategy_hypothesis_hash_present": False,
            "reference_data_sources_hash_present": False,
            "paper_shadow_reconciliation_hash_present": False,
            "scorecard_manifest_hash_present": False,
            "verdict_rationale_hash_present": False,
            "paper_shadow_window_trading_days": 0,
            "min_window_trading_days": 0,
            "independent_observation_count": 0,
            "min_independent_observation_count": 0,
            "gross_pnl_minor_units": 0,
            "net_pnl_minor_units": 0,
            "commission_minor_units": 0,
            "spread_slippage_minor_units": 0,
            "fx_drag_minor_units": 0,
            "tax_drag_minor_units": 0,
            "benchmark_excess_lcb_bps": 0,
            "conservative_cost_stress_lcb_bps": 0,
            "paper_shadow_divergence_bps": 0,
            "max_paper_shadow_divergence_bps": 0,
            "psr_bps": 0,
            "min_psr_bps": 0,
            "dsr_bps": 0,
            "min_dsr_bps": 0,
            "concentration_label_passed": False,
            "regime_label_passed": False,
            "breadth_label_passed": False,
            "freshness_label_passed": False,
            "survivorship_label_passed": False,
            "execution_realism_label_passed": False,
            "qc_review_hash_present": False,
            "mit_review_hash_present": False,
            "qa_review_hash_present": False,
            "qc_review_passed": False,
            "mit_review_passed": False,
            "qa_review_passed": False,
            "scorecard_is_derived_only": False,
            "paper_and_shadow_fills_separate": False,
            "live_fill_claimed": False,
            "bybit_live_execution_unchanged": False,
            "sealed": False,
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
            "secret_slot_touched": False,
            "order_routed": False,
        },
        "ibkr_live_enabled": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
        "live_or_tiny_live_authorized": False,
    }


def _valid_launch_status() -> dict[str, Any]:
    return {
        "phase": "phase5_launch_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "environment": "paper_shadow",
        "launch_status_state": "blocked",
        "phase3_started": False,
        "phase5_started": False,
        "release_packet": {
            "expected_contract_id": "stock_etf_release_packet_v1",
            "packet_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": [
                "packet_id_missing",
                "source_version_mismatch",
                "source_commit_missing",
            ],
            "paper_shadow_window_complete": False,
            "engineering_shakedown_complete": False,
            "role_report_count": 0,
            "manifest_hash_count": 0,
            "gui_screenshot_hash_count": 0,
            "dq_manifest_hash_count": 0,
            "scorecard_regeneration_hash_count": 0,
            "pg_migrations_declared": False,
            "pg_dry_run_log_hash_present": False,
            "pg_double_apply_log_hash_present": False,
            "redaction_fixture_hash_present": False,
            "evidence_archive_pointer_present": False,
            "evidence_archive_hash_present": False,
            "secret_content_serialized": False,
            "ibkr_live_or_tiny_live_authorized": False,
            "sealed": False,
        },
        "disable_cleanup_runbook": {
            "expected_runbook_id": "stock_etf_kill_switch_and_disable_cleanup_runbook_v1",
            "runbook_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": [
                "runbook_id_mismatch",
                "source_version_mismatch",
                "wrong_asset_lane",
                "wrong_broker",
            ],
            "bybit_live_execution_unchanged": False,
            "env_flag_count": 0,
            "proof_count": 0,
            "ibkr_contact_performed": False,
            "connector_runtime_started": False,
            "paper_order_routed": False,
            "secret_slot_created": False,
            "secret_content_serialized": False,
            "destructive_db_cleanup_requested": False,
            "db_delete_or_truncate_allowed": False,
            "paper_shadow_launch_authorized": False,
            "tiny_live_authorized": False,
            "live_authorized": False,
        },
        "tiny_live_adr_eligibility": {
            "expected_contract_id": "tiny_live_adr_eligibility_v1",
            "contract_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": [
                "contract_id_missing",
                "source_version_mismatch",
                "phase5_release_packet_hash_invalid",
            ],
            "decision": "not_eligible",
            "scorecard_derivation_hash_present": False,
            "scorecard_verdict_hash_present": False,
            "scorecard_manifest_hash_present": False,
            "paper_shadow_reconciliation_hash_present": False,
            "dq_manifest_hash_present": False,
            "statistical_preregistration_hash_present": False,
            "qc_review_hash_present": False,
            "mit_review_hash_present": False,
            "qa_review_hash_present": False,
            "paper_shadow_window_complete": False,
            "benchmark_relative_after_cost_lcb_bps": 0,
            "independent_observation_count": 0,
            "min_independent_observation_count": 0,
            "conservative_cost_stress_lcb_bps": 0,
            "paper_shadow_divergence_bps": 0,
            "max_paper_shadow_divergence_bps": 0,
            "concentration_label_passed": False,
            "regime_label_passed": False,
            "freshness_label_passed": False,
            "qc_review_passed": False,
            "mit_review_passed": False,
            "qa_review_passed": False,
            "secret_content_serialized": False,
            "sealed": False,
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
            "secret_slot_touched": False,
            "order_routed": False,
        },
        "ibkr_live_enabled": False,
        "paper_shadow_launch_authorized": False,
        "tiny_live_or_live_authorized": False,
        "connector_runtime_started": False,
        "scorecard_writer_started": False,
        "db_apply_performed": False,
        "evidence_clock_started": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
    }


def _valid_release_packet_status() -> dict[str, Any]:
    return {
        "phase": "phase5_release_packet_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "environment": "paper_shadow",
        "release_packet_status_state": "source_ready_runtime_blocked",
        "phase3_started": False,
        "phase5_started": False,
        "release_packet": {
            "expected_contract_id": "stock_etf_release_packet_v1",
            "packet_id": "stock_etf_release_packet_v1",
            "source_version": 1,
            "accepted": True,
            "blockers": [],
            "adr_path": "docs/adr/0048-ibkr-stock-etf-paper-shadow-lane.md",
            "amd_path": (
                "docs/governance_dev/amendments/"
                "2026-06-29--AMD-2026-06-29-01-ibkr-stock-etf-paper-shadow-lane.md"
            ),
            "spec_path": (
                "docs/execution_plan/specs/"
                "2026-06-29--stock_etf_cash_phase0_named_contract_packet.md"
            ),
            "source_commit_present": True,
            "created_at_ms": 1782800000000,
            "reviewer_role_count": 8,
            "reviewer_roles": ["PM", "Operator", "E2", "E3", "E4", "QA", "QC", "MIT"],
            "role_report_count": 2,
            "e2_log_hash_present": True,
            "e3_redaction_log_hash_present": True,
            "e4_log_hash_present": True,
            "qa_log_hash_present": True,
            "manifest_hash_count": 2,
            "manifest_hashes": [
                {"label": "release_manifest", "hash_present": True},
                {"label": "artifact_manifest", "hash_present": True},
            ],
            "pg_migrations_declared": False,
            "pg_migration_manifest_hash_present": False,
            "pg_dry_run_log_hash_present": False,
            "pg_double_apply_log_hash_present": False,
            "redaction_fixture_hash_present": True,
            "gui_screenshot_hash_count": 1,
            "dq_manifest_hash_count": 1,
            "scorecard_regeneration_hash_count": 1,
            "evidence_archive_pointer_present": True,
            "evidence_archive_hash_present": True,
            "paper_shadow_window_complete": True,
            "engineering_shakedown_complete": True,
            "secret_content_serialized": False,
            "ibkr_live_or_tiny_live_authorized": False,
            "sealed": True,
            "kill_disable_cleanup_proof": {
                "stock_etf_lane_enabled_false": True,
                "ibkr_readonly_enabled_false": True,
                "ibkr_paper_enabled_false": True,
                "stock_etf_shadow_only_true": True,
                "collector_stopped": True,
                "gui_stock_views_disabled_or_hidden": True,
                "live_secret_absence_proven": True,
                "evidence_archive_forward_only": True,
                "destructive_db_cleanup_requested": False,
                "proof_hash_present": True,
                "blockers": [],
            },
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
            "secret_slot_touched": False,
            "order_routed": False,
        },
        "ibkr_live_enabled": False,
        "paper_shadow_launch_authorized": False,
        "tiny_live_or_live_authorized": False,
        "connector_runtime_started": False,
        "scorecard_writer_started": False,
        "db_apply_performed": False,
        "evidence_clock_started": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
    }


def _valid_disable_cleanup_status() -> dict[str, Any]:
    return {
        "phase": "phase5_disable_cleanup_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "environment": "paper_shadow",
        "disable_cleanup_status_state": "source_ready_runtime_blocked",
        "phase3_started": False,
        "phase5_started": False,
        "collector_stop_requested": False,
        "gui_disable_requested": False,
        "evidence_archive_requested": False,
        "db_cleanup_requested": False,
        "runbook": {
            "expected_runbook_id": "stock_etf_kill_switch_and_disable_cleanup_runbook_v1",
            "runbook_id": "stock_etf_kill_switch_and_disable_cleanup_runbook_v1",
            "source_version": 1,
            "accepted": True,
            "blockers": [],
            "source_artifact_hash_present": True,
            "bybit_live_execution_unchanged": True,
            "env_flag_count": 4,
            "proof_count": 7,
            "env_flags": [
                {
                    "name": "OPENCLAW_STOCK_ETF_LANE_ENABLED",
                    "expected_value": "0",
                    "observed_value": "0",
                    "evidence_hash_present": True,
                },
                {
                    "name": "OPENCLAW_IBKR_READONLY_ENABLED",
                    "expected_value": "0",
                    "observed_value": "0",
                    "evidence_hash_present": True,
                },
                {
                    "name": "OPENCLAW_IBKR_PAPER_ENABLED",
                    "expected_value": "0",
                    "observed_value": "0",
                    "evidence_hash_present": True,
                },
                {
                    "name": "OPENCLAW_STOCK_ETF_SHADOW_ONLY",
                    "expected_value": "1",
                    "observed_value": "1",
                    "evidence_hash_present": True,
                },
            ],
            "proofs": [
                {
                    "kind": "collector_stopped",
                    "verified": True,
                    "evidence_hash_present": True,
                    "grants_runtime_authority": False,
                    "destructive_cleanup_claimed": False,
                },
                {
                    "kind": "gui_stock_views_disabled_or_hidden",
                    "verified": True,
                    "evidence_hash_present": True,
                    "grants_runtime_authority": False,
                    "destructive_cleanup_claimed": False,
                },
                {
                    "kind": "live_secret_absence_proven",
                    "verified": True,
                    "evidence_hash_present": True,
                    "grants_runtime_authority": False,
                    "destructive_cleanup_claimed": False,
                },
                {
                    "kind": "evidence_archive_forward_only",
                    "verified": True,
                    "evidence_hash_present": True,
                    "grants_runtime_authority": False,
                    "destructive_cleanup_claimed": False,
                },
                {
                    "kind": "db_forward_only_retention_preserved",
                    "verified": True,
                    "evidence_hash_present": True,
                    "grants_runtime_authority": False,
                    "destructive_cleanup_claimed": False,
                },
                {
                    "kind": "append_only_audit_preserved",
                    "verified": True,
                    "evidence_hash_present": True,
                    "grants_runtime_authority": False,
                    "destructive_cleanup_claimed": False,
                },
                {
                    "kind": "bybit_live_execution_unchanged",
                    "verified": True,
                    "evidence_hash_present": True,
                    "grants_runtime_authority": False,
                    "destructive_cleanup_claimed": False,
                },
            ],
            "ibkr_contact_performed": False,
            "connector_runtime_started": False,
            "paper_order_routed": False,
            "secret_slot_created": False,
            "secret_content_serialized": False,
            "destructive_db_cleanup_requested": False,
            "db_delete_or_truncate_allowed": False,
            "paper_shadow_launch_authorized": False,
            "tiny_live_authorized": False,
            "live_authorized": False,
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
            "secret_slot_touched": False,
            "order_routed": False,
        },
        "ibkr_live_enabled": False,
        "paper_shadow_launch_authorized": False,
        "tiny_live_or_live_authorized": False,
        "connector_runtime_started": False,
        "scorecard_writer_started": False,
        "db_apply_performed": False,
        "evidence_clock_started": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
    }


def _make_authless_client() -> TestClient:
    route_module._IPC_CLIENT = None
    app = FastAPI()
    app.include_router(stock_etf_router)
    return TestClient(app)
