//! HedgingEngine — Portfolio delta calculator and hedging recommendations.
//! 對沖引擎 — 組合 delta 計算器及對沖建議生成。
//!
//! Computes net delta across positions, identifies unhedged exposure,
//! and suggests hedging trades to neutralize portfolio risk.
//! 計算跨倉位淨 delta，識別未對沖敞口，建議對沖交易以中和組合風險。
//!
//! Thread-safe, pure computation, no side effects.
//! 線程安全，純計算，無副作用。

use pyo3::prelude::*;
use std::collections::HashMap;

/// A single position in the portfolio / 投資組合中的單個倉位
#[pyclass]
#[derive(Clone)]
pub struct Position {
    /// Trading symbol / 交易品種
    #[pyo3(get)]
    pub symbol: String,
    /// Position side: "long" or "short" / 倉位方向："long" 或 "short"
    #[pyo3(get)]
    pub side: String,
    /// Position quantity / 倉位數量
    #[pyo3(get)]
    pub qty: f64,
    /// Entry price / 入場價格
    #[pyo3(get)]
    pub entry_price: f64,
    /// Current market price / 當前市場價格
    #[pyo3(get)]
    pub current_price: f64,
    /// Contract category: "linear", "spot", or "inverse" / 合約類型
    #[pyo3(get)]
    pub category: String,
}

#[pymethods]
impl Position {
    /// Create a new Position / 創建新倉位
    #[new]
    #[pyo3(signature = (symbol, side, qty, entry_price, current_price, category="linear".to_string()))]
    fn new(
        symbol: String,
        side: String,
        qty: f64,
        entry_price: f64,
        current_price: f64,
        category: String,
    ) -> Self {
        Position {
            symbol,
            side,
            qty,
            entry_price,
            current_price,
            category,
        }
    }
}

/// A hedging recommendation generated by the engine / 引擎生成的對沖建議
#[pyclass]
#[derive(Clone)]
pub struct HedgeRecommendation {
    /// Symbol to hedge / 需對沖的品種
    #[pyo3(get)]
    pub symbol: String,
    /// Recommended side: "Buy" or "Sell" / 建議方向
    #[pyo3(get)]
    pub side: String,
    /// Recommended quantity / 建議數量
    #[pyo3(get)]
    pub qty: f64,
    /// Reason for the recommendation (bilingual) / 建議原因（雙語）
    #[pyo3(get)]
    pub reason: String,
    /// Urgency score 0.0–1.0 / 緊迫度評分
    #[pyo3(get)]
    pub urgency: f64,
}

#[pymethods]
impl HedgeRecommendation {
    /// Convert to dict for Python consumption / 轉換為字典供 Python 使用
    fn to_dict(&self) -> HashMap<String, String> {
        let mut m = HashMap::new();
        m.insert("symbol".to_string(), self.symbol.clone());
        m.insert("side".to_string(), self.side.clone());
        m.insert("qty".to_string(), format!("{:.6}", self.qty));
        m.insert("reason".to_string(), self.reason.clone());
        m.insert("urgency".to_string(), format!("{:.4}", self.urgency));
        m
    }
}

/// HedgingEngine — computes portfolio delta and generates hedge recommendations.
/// 對沖引擎 — 計算組合 delta 並生成對沖建議。
///
/// All methods take &self (immutable) — no interior mutability needed.
/// 所有方法接受 &self（不可變引用）— 無需內部可變性。
#[pyclass]
pub struct HedgingEngine {
    /// Maximum allowed delta as percentage of equity / 最大允許 delta 百分比
    max_delta_pct: f64,
    /// Threshold to trigger hedge recommendation / 觸發對沖建議的閾值百分比
    hedge_threshold_pct: f64,
}

#[pymethods]
impl HedgingEngine {
    /// Create a new HedgingEngine with configurable thresholds.
    /// 創建帶可配置閾值的新對沖引擎。
    ///
    /// - max_delta_pct: maximum tolerated delta % (default 5.0)
    /// - hedge_threshold_pct: delta % that triggers recommendations (default 3.0)
    #[new]
    #[pyo3(signature = (max_delta_pct=None, hedge_threshold_pct=None))]
    fn new(max_delta_pct: Option<f64>, hedge_threshold_pct: Option<f64>) -> Self {
        HedgingEngine {
            max_delta_pct: max_delta_pct.unwrap_or(5.0),
            hedge_threshold_pct: hedge_threshold_pct.unwrap_or(3.0),
        }
    }

    /// Compute per-symbol net delta in USD.
    /// 計算每個品種的淨 delta（USD 計價）。
    ///
    /// - linear/spot: delta = ±qty * current_price
    /// - inverse: delta = ±qty / current_price (contract value denominated in base)
    /// 正向/現貨：delta = ±qty * current_price
    /// 反向合約：delta = ±qty / current_price（合約價值以基礎幣計價）
    fn compute_portfolio_delta(&self, positions: Vec<Position>) -> PyResult<HashMap<String, f64>> {
        // Delegate to internal helper to avoid duplicated logic
        // 委託給內部方法以避免重複邏輯
        Ok(self.compute_symbol_deltas(&positions))
    }

    /// Compute total net delta across all positions in USD.
    /// 計算所有倉位的總淨 delta（USD 計價）。
    fn compute_net_delta(&self, positions: Vec<Position>) -> f64 {
        positions.iter().map(Self::position_delta).sum()
    }

    /// Generate hedging recommendations for positions exceeding threshold.
    /// 為超過閾值的倉位生成對沖建議。
    ///
    /// For each symbol whose |delta| / account_equity > hedge_threshold_pct%,
    /// produce a HedgeRecommendation to neutralize the exposure.
    /// 對每個 |delta| / 帳戶權益 > hedge_threshold_pct% 的品種，
    /// 生成對沖建議以中和敞口。
    fn get_hedge_recommendations(
        &self,
        positions: Vec<Position>,
        account_equity: f64,
    ) -> Vec<HedgeRecommendation> {
        // Guard: zero or negative equity → no recommendations
        // 防護：零或負權益 → 不生成建議
        if account_equity <= 0.0 {
            return Vec::new();
        }

        let deltas = self.compute_symbol_deltas(&positions);
        let threshold = self.hedge_threshold_pct / 100.0;
        let max_pct = self.max_delta_pct / 100.0;
        let mut recommendations = Vec::new();

        // Build a price lookup for qty calculation
        // 建立價格查詢表用於計算數量
        let mut price_map: HashMap<&str, (f64, &str)> = HashMap::new();
        for pos in &positions {
            price_map
                .entry(&pos.symbol)
                .or_insert((pos.current_price, &pos.category));
        }

        for (symbol, net_delta) in &deltas {
            let delta_pct = net_delta.abs() / account_equity;

            if delta_pct > threshold {
                // Hedge direction: positive delta → Sell, negative → Buy
                // 對沖方向：正 delta → 賣出，負 delta → 買入
                let side = if *net_delta > 0.0 { "Sell" } else { "Buy" };

                // Qty to neutralize: |delta| / price (or * price for inverse)
                // 中和所需數量：|delta| / 價格（反向合約為 * 價格）
                let hedge_qty = if let Some(&(price, category)) = price_map.get(symbol.as_str()) {
                    if price > 0.0 {
                        if category == "inverse" {
                            net_delta.abs() * price
                        } else {
                            net_delta.abs() / price
                        }
                    } else {
                        0.0
                    }
                } else {
                    0.0
                };

                // Urgency: clamped ratio of delta_pct to max_delta_pct
                // 緊迫度：delta_pct 與 max_delta_pct 的比值（上限 1.0）
                let urgency = if max_pct > 0.0 {
                    (delta_pct / max_pct).min(1.0)
                } else {
                    1.0
                };

                let reason = format!(
                    "Delta exposure {:.2}% exceeds threshold {:.2}% — need to {} to reduce risk / \
                     Delta 敞口 {:.2}% 超過閾值 {:.2}% — 需要{}以降低風險",
                    delta_pct * 100.0,
                    self.hedge_threshold_pct,
                    side.to_lowercase(),
                    delta_pct * 100.0,
                    self.hedge_threshold_pct,
                    if side == "Sell" { "賣出" } else { "買入" },
                );

                recommendations.push(HedgeRecommendation {
                    symbol: symbol.clone(),
                    side: side.to_string(),
                    qty: hedge_qty,
                    reason,
                    urgency,
                });
            }
        }

        // Sort by urgency descending for prioritization / 按緊迫度降序排列以確定優先級
        recommendations.sort_by(|a, b| b.urgency.partial_cmp(&a.urgency).unwrap_or(std::cmp::Ordering::Equal));

        recommendations
    }

    /// Return engine configuration status / 返回引擎配置狀態
    fn get_status(&self) -> HashMap<String, String> {
        let mut status = HashMap::new();
        status.insert("engine".to_string(), "HedgingEngine".to_string());
        status.insert("max_delta_pct".to_string(), format!("{:.2}", self.max_delta_pct));
        status.insert(
            "hedge_threshold_pct".to_string(),
            format!("{:.2}", self.hedge_threshold_pct),
        );
        status.insert("version".to_string(), "1.0.0".to_string());
        status
    }
}

/// Internal (non-PyO3) helpers / 內部輔助方法（非 PyO3）
impl HedgingEngine {
    /// Compute delta for a single position / 計算單個倉位的 delta
    fn position_delta(pos: &Position) -> f64 {
        let sign = match pos.side.to_lowercase().as_str() {
            "long" => 1.0,
            "short" => -1.0,
            _ => 0.0, // Unknown side → zero delta (safe default) / 未知方向 → 零 delta（安全默認）
        };

        if pos.category == "inverse" {
            // Inverse contract: delta = ±qty / current_price
            // 反向合約：delta = ±qty / current_price
            if pos.current_price > 0.0 {
                sign * pos.qty / pos.current_price
            } else {
                0.0
            }
        } else {
            // Linear / spot: delta = ±qty * current_price
            // 正向 / 現貨：delta = ±qty * current_price
            sign * pos.qty * pos.current_price
        }
    }

    /// Compute per-symbol deltas (internal reuse) / 計算每品種 delta（內部複用）
    fn compute_symbol_deltas(&self, positions: &[Position]) -> HashMap<String, f64> {
        let mut deltas: HashMap<String, f64> = HashMap::new();
        for pos in positions {
            let raw_delta = Self::position_delta(pos);
            let entry = deltas.entry(pos.symbol.clone()).or_insert(0.0);
            *entry += raw_delta;
        }
        deltas
    }
}
