from __future__ import annotations

from typing import Any

from .phase2_payloads import _valid_api_allowlist


def _valid_launch_status() -> dict[str, Any]:
    return {
        "phase": "phase5_launch_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "environment": "paper_shadow",
        "launch_status_state": "blocked",
        "phase3_started": False,
        "phase5_started": False,
        "release_packet": {
            "expected_contract_id": "stock_etf_release_packet_v1",
            "packet_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": [
                "packet_id_missing",
                "source_version_mismatch",
                "source_commit_missing",
            ],
            "paper_shadow_window_complete": False,
            "engineering_shakedown_complete": False,
            "role_report_count": 0,
            "manifest_hash_count": 0,
            "gui_screenshot_hash_count": 0,
            "dq_manifest_hash_count": 0,
            "scorecard_regeneration_hash_count": 0,
            "pg_migrations_declared": False,
            "pg_dry_run_log_hash_present": False,
            "pg_double_apply_log_hash_present": False,
            "redaction_fixture_hash_present": False,
            "evidence_archive_pointer_present": False,
            "evidence_archive_hash_present": False,
            "secret_content_serialized": False,
            "ibkr_live_or_tiny_live_authorized": False,
            "sealed": False,
        },
        "disable_cleanup_runbook": {
            "expected_runbook_id": "stock_etf_kill_switch_and_disable_cleanup_runbook_v1",
            "runbook_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": [
                "runbook_id_mismatch",
                "source_version_mismatch",
                "wrong_asset_lane",
                "wrong_broker",
            ],
            "bybit_live_execution_unchanged": False,
            "env_flag_count": 0,
            "proof_count": 0,
            "ibkr_contact_performed": False,
            "connector_runtime_started": False,
            "paper_order_routed": False,
            "secret_slot_created": False,
            "secret_content_serialized": False,
            "destructive_db_cleanup_requested": False,
            "db_delete_or_truncate_allowed": False,
            "paper_shadow_launch_authorized": False,
            "tiny_live_authorized": False,
            "live_authorized": False,
        },
        "tiny_live_adr_eligibility": {
            "expected_contract_id": "tiny_live_adr_eligibility_v1",
            "contract_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": [
                "contract_id_missing",
                "source_version_mismatch",
                "phase5_release_packet_hash_invalid",
            ],
            "decision": "not_eligible",
            "scorecard_derivation_hash_present": False,
            "scorecard_verdict_hash_present": False,
            "scorecard_manifest_hash_present": False,
            "paper_shadow_reconciliation_hash_present": False,
            "dq_manifest_hash_present": False,
            "statistical_preregistration_hash_present": False,
            "qc_review_hash_present": False,
            "mit_review_hash_present": False,
            "qa_review_hash_present": False,
            "paper_shadow_window_complete": False,
            "benchmark_relative_after_cost_lcb_bps": 0,
            "independent_observation_count": 0,
            "min_independent_observation_count": 0,
            "conservative_cost_stress_lcb_bps": 0,
            "paper_shadow_divergence_bps": 0,
            "max_paper_shadow_divergence_bps": 0,
            "concentration_label_passed": False,
            "regime_label_passed": False,
            "freshness_label_passed": False,
            "qc_review_passed": False,
            "mit_review_passed": False,
            "qa_review_passed": False,
            "secret_content_serialized": False,
            "sealed": False,
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
            "secret_slot_touched": False,
            "order_routed": False,
        },
        "ibkr_live_enabled": False,
        "paper_shadow_launch_authorized": False,
        "tiny_live_or_live_authorized": False,
        "connector_runtime_started": False,
        "scorecard_writer_started": False,
        "db_apply_performed": False,
        "evidence_clock_started": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
    }


def _valid_release_packet_status() -> dict[str, Any]:
    return {
        "phase": "phase5_release_packet_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "environment": "paper_shadow",
        "release_packet_status_state": "source_ready_runtime_blocked",
        "phase3_started": False,
        "phase5_started": False,
        "release_packet": {
            "expected_contract_id": "stock_etf_release_packet_v1",
            "packet_id": "stock_etf_release_packet_v1",
            "source_version": 1,
            "accepted": True,
            "blockers": [],
            "adr_path": "docs/adr/0048-ibkr-stock-etf-paper-shadow-lane.md",
            "amd_path": (
                "docs/governance_dev/amendments/"
                "2026-06-29--AMD-2026-06-29-01-ibkr-stock-etf-paper-shadow-lane.md"
            ),
            "spec_path": (
                "docs/execution_plan/specs/"
                "2026-06-29--stock_etf_cash_phase0_named_contract_packet.md"
            ),
            "source_commit_present": True,
            "created_at_ms": 1782800000000,
            "reviewer_role_count": 8,
            "reviewer_roles": ["PM", "Operator", "E2", "E3", "E4", "QA", "QC", "MIT"],
            "role_report_count": 2,
            "e2_log_hash_present": True,
            "e3_redaction_log_hash_present": True,
            "e4_log_hash_present": True,
            "qa_log_hash_present": True,
            "manifest_hash_count": 2,
            "manifest_hashes": [
                {"label": "release_manifest", "hash_present": True},
                {"label": "artifact_manifest", "hash_present": True},
            ],
            "pg_migrations_declared": False,
            "pg_migration_manifest_hash_present": False,
            "pg_dry_run_log_hash_present": False,
            "pg_double_apply_log_hash_present": False,
            "redaction_fixture_hash_present": True,
            "gui_screenshot_hash_count": 1,
            "dq_manifest_hash_count": 1,
            "scorecard_regeneration_hash_count": 1,
            "evidence_archive_pointer_present": True,
            "evidence_archive_hash_present": True,
            "paper_shadow_window_complete": True,
            "engineering_shakedown_complete": True,
            "secret_content_serialized": False,
            "ibkr_live_or_tiny_live_authorized": False,
            "sealed": True,
            "kill_disable_cleanup_proof": {
                "stock_etf_lane_enabled_false": True,
                "ibkr_readonly_enabled_false": True,
                "ibkr_paper_enabled_false": True,
                "stock_etf_shadow_only_true": True,
                "collector_stopped": True,
                "gui_stock_views_disabled_or_hidden": True,
                "live_secret_absence_proven": True,
                "evidence_archive_forward_only": True,
                "destructive_db_cleanup_requested": False,
                "proof_hash_present": True,
                "blockers": [],
            },
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
            "secret_slot_touched": False,
            "order_routed": False,
        },
        "ibkr_live_enabled": False,
        "paper_shadow_launch_authorized": False,
        "tiny_live_or_live_authorized": False,
        "connector_runtime_started": False,
        "scorecard_writer_started": False,
        "db_apply_performed": False,
        "evidence_clock_started": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
    }


def _valid_disable_cleanup_status() -> dict[str, Any]:
    return {
        "phase": "phase5_disable_cleanup_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "environment": "paper_shadow",
        "disable_cleanup_status_state": "source_ready_runtime_blocked",
        "phase3_started": False,
        "phase5_started": False,
        "collector_stop_requested": False,
        "gui_disable_requested": False,
        "evidence_archive_requested": False,
        "db_cleanup_requested": False,
        "runbook": {
            "expected_runbook_id": "stock_etf_kill_switch_and_disable_cleanup_runbook_v1",
            "runbook_id": "stock_etf_kill_switch_and_disable_cleanup_runbook_v1",
            "source_version": 1,
            "accepted": True,
            "blockers": [],
            "source_artifact_hash_present": True,
            "bybit_live_execution_unchanged": True,
            "env_flag_count": 4,
            "proof_count": 7,
            "env_flags": [
                {
                    "name": "OPENCLAW_STOCK_ETF_LANE_ENABLED",
                    "expected_value": "0",
                    "observed_value": "0",
                    "evidence_hash_present": True,
                },
                {
                    "name": "OPENCLAW_IBKR_READONLY_ENABLED",
                    "expected_value": "0",
                    "observed_value": "0",
                    "evidence_hash_present": True,
                },
                {
                    "name": "OPENCLAW_IBKR_PAPER_ENABLED",
                    "expected_value": "0",
                    "observed_value": "0",
                    "evidence_hash_present": True,
                },
                {
                    "name": "OPENCLAW_STOCK_ETF_SHADOW_ONLY",
                    "expected_value": "1",
                    "observed_value": "1",
                    "evidence_hash_present": True,
                },
            ],
            "proofs": [
                {
                    "kind": "collector_stopped",
                    "verified": True,
                    "evidence_hash_present": True,
                    "grants_runtime_authority": False,
                    "destructive_cleanup_claimed": False,
                },
                {
                    "kind": "gui_stock_views_disabled_or_hidden",
                    "verified": True,
                    "evidence_hash_present": True,
                    "grants_runtime_authority": False,
                    "destructive_cleanup_claimed": False,
                },
                {
                    "kind": "live_secret_absence_proven",
                    "verified": True,
                    "evidence_hash_present": True,
                    "grants_runtime_authority": False,
                    "destructive_cleanup_claimed": False,
                },
                {
                    "kind": "evidence_archive_forward_only",
                    "verified": True,
                    "evidence_hash_present": True,
                    "grants_runtime_authority": False,
                    "destructive_cleanup_claimed": False,
                },
                {
                    "kind": "db_forward_only_retention_preserved",
                    "verified": True,
                    "evidence_hash_present": True,
                    "grants_runtime_authority": False,
                    "destructive_cleanup_claimed": False,
                },
                {
                    "kind": "append_only_audit_preserved",
                    "verified": True,
                    "evidence_hash_present": True,
                    "grants_runtime_authority": False,
                    "destructive_cleanup_claimed": False,
                },
                {
                    "kind": "bybit_live_execution_unchanged",
                    "verified": True,
                    "evidence_hash_present": True,
                    "grants_runtime_authority": False,
                    "destructive_cleanup_claimed": False,
                },
            ],
            "ibkr_contact_performed": False,
            "connector_runtime_started": False,
            "paper_order_routed": False,
            "secret_slot_created": False,
            "secret_content_serialized": False,
            "destructive_db_cleanup_requested": False,
            "db_delete_or_truncate_allowed": False,
            "paper_shadow_launch_authorized": False,
            "tiny_live_authorized": False,
            "live_authorized": False,
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
            "secret_slot_touched": False,
            "order_routed": False,
        },
        "ibkr_live_enabled": False,
        "paper_shadow_launch_authorized": False,
        "tiny_live_or_live_authorized": False,
        "connector_runtime_started": False,
        "scorecard_writer_started": False,
        "db_apply_performed": False,
        "evidence_clock_started": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
    }
