from __future__ import annotations

from typing import Any


def _valid_api_allowlist() -> dict[str, Any]:
    return {
        "contract_id": "non_bybit_api_allowlist_v1",
        "source_version": 1,
        "accepted": True,
        "blockers": [],
        "read_action_count": 10,
        "paper_write_action_count": 3,
        "denied_action_count": 10,
        "ibkr_contact_performed": False,
        "secret_content_serialized": False,
        "bybit_live_execution_protected": True,
    }


def _valid_phase0_status() -> dict[str, Any]:
    return {
        "phase": "phase0_contract_packet_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "scope": "paper_shadow_only",
        "gui_authority": "display_only",
        "phase0_status_state": "accepted_no_runtime_authority",
        "phase0_accepted": True,
        "phase0_blockers": [],
        "contract_count": 36,
        "contracts": [
            "asset_lane_taxonomy_v1",
            "broker_capability_registry_v1",
            "phase2_ibkr_external_surface_gate_v1",
            "non_bybit_api_allowlist_v1",
            "stock_etf_ibkr_readonly_probe_request_v1",
            "stock_etf_ibkr_readonly_probe_result_import_request_v1",
            "instrument_identity_contract_v1",
            "stock_etf_pit_universe_contract_v1",
            "stock_etf_strategy_hypothesis_contract_v1",
            "stock_etf_risk_policy_v1",
            "stock_etf_reference_data_sources_v1",
            "ibkr_api_session_topology_v1",
            "ibkr_session_attestation_v1",
            "feature_flag_secret_auth_matrix_v1",
            "lane_scoped_ipc_v1",
            "stock_etf_paper_order_request_v1",
            "stock_etf_paper_fill_import_request_v1",
            "stock_etf_shadow_signal_request_v1",
            "ibkr_paper_order_lifecycle_v1",
            "broker_lifecycle_event_log_v1",
            "audit.asset_lane_events_v1",
            "stock_etf_db_evidence_ddl_v1",
            "stock_market_data_provenance_v1",
            "broker_account_portfolio_cash_ledger_v1",
            "cost_model_version_v1",
            "benchmark_versions_v1",
            "stock_shadow_fill_model_v1",
            "stock_etf_paper_shadow_reconciliation_v1",
            "stock_etf_collector_run_v1",
            "stock_etf_dq_manifest_v1",
            "stock_etf_evidence_clock_v1",
            "gui_lane_contract_v1",
            "stock_etf_storage_capacity_v1",
            "stock_etf_kill_switch_and_disable_cleanup_runbook_v1",
            "stock_etf_release_packet_v1",
            "tiny_live_adr_eligibility_v1",
        ],
        "manifest": {
            "schema": "stock_etf_phase0_contract_packet_manifest_v1",
            "generated_at": "2026-06-29",
            "status": "ACCEPTED_PHASE0_CONTRACT_NO_RUNTIME_AUTHORITY",
            "scope": "paper_shadow_only",
            "adr": "docs/adr/0048-ibkr-stock-etf-paper-shadow-lane.md",
            "amd": "docs/governance_dev/amendments/2026-06-29--AMD-2026-06-29-01-ibkr-stock-etf-paper-shadow-lane.md",
            "contract_packet": "docs/execution_plan/specs/2026-06-29--stock_etf_cash_phase0_named_contract_packet.md",
        },
        "api_baseline": {
            "selected": "ib_gateway_tws_api",
            "host_policy": "loopback_only",
            "paper_port_default_candidate": 4002,
            "live_ports_denied": True,
            "ibkr_call_performed": False,
        },
        "global_denials": {
            "ibkr_live": True,
            "tiny_live": True,
            "margin": True,
            "short": True,
            "options": True,
            "cfd": True,
            "transfer": True,
            "account_management_writes": True,
            "python_broker_write_authority": True,
            "gui_lane_authority": True,
            "automatic_promotion": True,
        },
        "phase_unlock": {
            "phase1_type_config_schema_ipc": "ALLOWED_AFTER_THIS_PACKET_WITH_E2_E4_QA",
            "phase2_ibkr_external_contact": "BLOCKED_UNTIL_PHASE2_EXTERNAL_SURFACE_GATE_PASS",
            "phase3_evidence_clock": "BLOCKED_UNTIL_DATA_PROVENANCE_EVIDENCE_CONTRACTS_PASS",
            "phase4_gui_runtime": "BLOCKED_UNTIL_ROUTE_CACHE_AUTH_NEGATIVE_TESTS_PASS",
            "phase5_paper_shadow_online": "BLOCKED_UNTIL_RELEASE_PACKET_AND_SHAKEDOWN_PASS",
            "tiny_live_or_live": "BLOCKED_REQUIRES_FUTURE_ADR",
        },
        "phase1_runtime_started": False,
        "phase2_started": False,
        "phase3_started": False,
        "phase4_runtime_started": False,
        "phase5_started": False,
        "paper_shadow_launch_authorized": False,
        "tiny_live_or_live_authorized": False,
        "connector_runtime_started": False,
        "db_apply_performed": False,
        "evidence_clock_started": False,
        "scorecard_writer_started": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
    }


def _valid_lane_status() -> dict[str, Any]:
    return {
        "phase": "phase2_precontact_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "default_asset_lane": "crypto_perp",
        "flags": {
            "stock_etf_lane_enabled": True,
            "ibkr_readonly_enabled": True,
            "ibkr_paper_enabled": False,
            "asset_lane_default": "crypto_perp",
            "stock_etf_shadow_only": True,
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
        },
        "ibkr_live_enabled": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
    }


def _valid_data_foundation_status() -> dict[str, Any]:
    return {
        "phase": "phase2_data_foundation_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "environment": "paper",
        "data_foundation_status_state": "blocked",
        "phase2_started": False,
        "phase3_started": False,
        "contract_details_request_started": False,
        "reference_data_collection_started": False,
        "collector_started": False,
        "market_data_ingestion_started": False,
        "connector_runtime_started": False,
        "db_apply_performed": False,
        "evidence_clock_started": False,
        "scorecard_writer_started": False,
        "instrument_identity": {
            "expected_contract_id": "instrument_identity_contract_v1",
            "contract_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": ["contract_id_mismatch", "source_version_mismatch"],
            "symbol": "",
            "instrument_kind": "stock",
            "listing_venue": "unknown_denied",
            "primary_exchange": "unknown_denied",
            "currency": "unknown_denied",
            "tradability_status": "unknown_denied",
            "priips_kid_status": "unknown_denied",
            "fractional_policy_recorded": False,
            "point_in_time_asof_ms": 0,
            "market_calendar_id_present": False,
            "market_calendar_hash_present": False,
            "broker_contract_details_hash_present": False,
            "instrument_identity_hash_present": False,
            "corporate_action_adjustment_version_hash_present": False,
            "source_artifact_hash_present": False,
            "bybit_live_execution_unchanged": True,
            "ibkr_live_denied": True,
            "margin_short_denied": True,
            "options_cfd_denied": True,
            "ibkr_contact_performed": False,
            "secret_content_serialized": False,
        },
        "reference_data_sources": {
            "expected_contract_id": "stock_etf_reference_data_sources_v1",
            "contract_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": ["contract_id_mismatch", "source_version_mismatch"],
            "environment": "paper",
            "frozen_for_evidence_clock": False,
            "corporate_action_source_name": "",
            "corporate_action_asof_ms": 0,
            "corporate_action_raw_hash_present": False,
            "corporate_action_adjustment_version_hash_present": False,
            "corporate_action_policy_hash_present": False,
            "dividend_treatment_hash_present": False,
            "fx_rate_source_name": "",
            "fx_rate_asof_ms": 0,
            "base_currency": "unknown_denied",
            "quote_currency": "unknown_denied",
            "fx_rate_snapshot_hash_present": False,
            "fx_drag_model_hash_present": False,
            "fee_schedule_source_name": "",
            "fee_schedule_asof_ms": 0,
            "commission_schedule_hash_present": False,
            "exchange_regulatory_fee_hash_present": False,
            "tax_ftt_placeholder_hash_present": False,
            "withholding_tax_treatment_hash_present": False,
            "source_artifact_hash_present": False,
            "bybit_live_execution_unchanged": True,
            "ibkr_contact_performed": False,
            "connector_runtime_started": False,
            "secret_content_serialized": False,
            "live_or_tiny_live_authorized": False,
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
            "secret_slot_touched": False,
            "order_routed": False,
        },
        "ibkr_live_enabled": False,
        "stock_live_disabled": True,
        "paper_order_entry_visible": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
    }


def _valid_policy_status() -> dict[str, Any]:
    return {
        "phase": "phase2_policy_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "environment": "paper",
        "policy_status_state": "blocked",
        "phase2_started": False,
        "phase3_started": False,
        "risk_runtime_started": False,
        "paper_order_rehearsal_started": False,
        "paper_order_submitted": False,
        "connector_runtime_started": False,
        "db_apply_performed": False,
        "evidence_clock_started": False,
        "scorecard_writer_started": False,
        "risk_policy": {
            "expected_contract_id": "stock_etf_risk_policy_v1",
            "contract_id": "",
            "source_version": 0,
            "config_version": 0,
            "accepted": False,
            "blockers": ["contract_id_mismatch", "source_version_mismatch"],
            "environment": "paper",
            "enabled": False,
            "shadow_only": True,
            "max_order_notional_usd": 0,
            "max_position_notional_usd": 0,
            "max_daily_notional_usd": 0,
            "max_open_orders": 0,
            "max_open_positions": 0,
            "allow_fractional_shares": False,
            "allow_margin": False,
            "allow_short": False,
            "allow_options": False,
            "allow_cfd": False,
            "allow_transfer": False,
            "allow_live": False,
            "allowed_kind_count": 0,
            "denied_kind_count": 0,
            "requires_frozen_universe_hash": False,
            "requires_instrument_identity_hash": False,
            "requires_market_session": False,
            "cost_model_required_before_shadow_fill": False,
            "cost_model_required_before_scorecard": False,
            "commission_schedule_required": False,
            "spread_estimate_required": False,
            "slippage_estimate_required": False,
            "fx_drag_required": False,
            "conservative_fill_penalty_required": False,
            "rust_authority_required": False,
            "session_attestation_required": False,
            "decision_lease_required": False,
            "guardian_required": False,
            "idempotency_key_required": False,
            "broker_reconciliation_required": False,
            "bybit_live_execution_unchanged": True,
            "ibkr_contact_performed": False,
            "connector_runtime_started": False,
            "secret_content_serialized": False,
        },
        "broker_capability_registry": {
            "expected_registry_id": "broker_capability_registry_v1",
            "registry_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": ["registry_id_mismatch", "source_version_mismatch"],
            "operation_count": 0,
            "required_audit_field_count": 0,
            "read_operation_count": 0,
            "lane_scoped_ipc_contract_id": "lane_scoped_ipc_v1",
            "readonly_probe_request_contract_id": (
                "stock_etf_ibkr_readonly_probe_request_v1"
            ),
            "readonly_probe_result_import_request_contract_id": (
                "stock_etf_ibkr_readonly_probe_result_import_request_v1"
            ),
            "read_rows_require_lane_scoped_ipc": False,
            "read_rows_require_readonly_probe_request": False,
            "scorecard_requires_readonly_probe_result_import_request": False,
            "paper_operation_count": 0,
            "denied_operation_count": 0,
            "bybit_live_execution_unchanged": True,
            "python_broker_write_authority_denied": True,
            "ibkr_live_denied": True,
            "cfd_margin_reserved_denied": True,
            "first_ibkr_contact_performed": False,
            "secret_content_serialized": False,
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
            "secret_slot_touched": False,
            "order_routed": False,
        },
        "ibkr_live_enabled": False,
        "stock_live_disabled": True,
        "paper_order_entry_visible": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
    }


def _valid_authorization_status() -> dict[str, Any]:
    return {
        "phase": "phase2_authorization_status_source_fixture",
        "asset_lane": "stock_etf_cash",
        "broker": "ibkr",
        "environment": "paper",
        "authorization_status_state": "blocked",
        "phase2_started": False,
        "phase3_started": False,
        "risk_runtime_started": False,
        "paper_order_rehearsal_started": False,
        "paper_order_submitted": False,
        "connector_runtime_started": False,
        "db_apply_performed": False,
        "evidence_clock_started": False,
        "scorecard_writer_started": False,
        "paper_order_authority_present": False,
        "scoped_authorization_present": False,
        "decision_lease_valid": False,
        "guardian_allows": False,
        "authorization_matrix": {
            "expected_contract_id": "feature_flag_secret_auth_matrix_v1",
            "contract_id": "",
            "source_version": 0,
            "gui_lane_state_override_denied": True,
            "server_rust_matrix_authoritative": True,
            "request_asset_lane": "stock_etf_cash",
            "request_broker": "ibkr",
            "request_environment": "paper",
            "request_instrument_kind": "stock",
            "request_operation": "paper_order_submit",
            "request_allowed": False,
            "effective_authority_scope": "denied",
            "blockers": ["contract_id_mismatch", "source_version_mismatch"],
        },
        "feature_flags": {
            "stock_etf_lane_enabled": False,
            "ibkr_readonly_enabled": False,
            "ibkr_paper_enabled": False,
            "asset_lane_default": "crypto_perp",
            "stock_etf_shadow_only": True,
        },
        "secret_slot_contract": {
            "expected_contract_id": "ibkr_secret_slot_contract_v1",
            "contract_id": "",
            "source_version": 0,
            "accepted": False,
            "blockers": ["contract_id_mismatch", "source_version_mismatch"],
            "contract_present": False,
            "readonly_slot_posture": "unknown",
            "paper_slot_posture": "unknown",
            "live_slot_posture": "unknown",
            "owner_only_permissions": False,
            "env_var_credential_fallback_denied": False,
            "live_secret_absent_or_empty": False,
            "secret_slot_fingerprint_present": False,
            "account_fingerprint_hash_present": False,
            "secret_content_serialized": False,
            "account_id_serialized": False,
        },
        "phase2_gate_artifact": {
            "expected_contract_id": "phase2_ibkr_external_surface_gate_v1",
            "contract_id": "",
            "source_version": 0,
            "ibkr_contact_allowed": False,
            "blockers": ["contract_id_mismatch", "source_version_mismatch"],
            "artifact_id_present": False,
            "sealed": False,
            "raw_artifact_hash_present": False,
            "redacted_summary_hash_present": False,
        },
        "session_attestation": {
            "expected_contract_id": "ibkr_session_attestation_v1",
            "contract_id": "",
            "source_version": 0,
            "status": "BLOCKED",
            "attestation_accepted": False,
            "blockers": ["contract_id_mismatch", "source_version_mismatch"],
            "environment": "read_only",
            "account_fingerprint_present": False,
            "account_fingerprint_is_live": False,
            "secret_slot_fingerprint_present": False,
            "api_server_version_present": False,
            "data_tier": "unknown",
            "entitlements_fingerprint_present": False,
            "market_data_entitlement_purchase_denied": False,
            "gateway_started_at_ms": 0,
            "raw_artifact_hash_present": False,
        },
        "authorization_envelope": {
            "asset_lane": "stock_etf_cash",
            "broker": "ibkr",
            "environment": "paper",
            "permission_scope": "denied",
            "secret_slot_fingerprint_present": False,
            "account_fingerprint_hash_present": False,
            "risk_config_hash_present": False,
            "expires_at_ms": 0,
        },
        "phase2": {
            "external_surface_gate": {
                "status": "BLOCKED",
                "ibkr_contact_allowed": False,
                "blockers": ["status_not_pass"],
                "ibkr_call_performed": False,
            },
            "api_allowlist": _valid_api_allowlist(),
            "immutable_pass_artifact_present": False,
            "first_ibkr_contact_allowed": False,
            "connector_enabled": False,
            "secret_slot_touched": False,
            "order_routed": False,
        },
        "ibkr_live_enabled": False,
        "stock_live_disabled": True,
        "paper_order_entry_visible": False,
        "ibkr_call_performed": False,
        "secret_slot_touched": False,
        "order_routed": False,
        "bybit_ipc_reused": False,
    }
