#!/usr/bin/env python3
import json
import subprocess
from pathlib import Path

CHECK_SCRIPT = Path("/home/ncyu/srv/program_code/exchange_connectors/bybit_connector/scripts/bybit_public_connectivity_check.py")

def run_check() -> dict:
    result = subprocess.run(
        ["python3", str(CHECK_SCRIPT)],
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(result.stdout)

def psql_exec(sql: str) -> None:
    subprocess.run(
        [
            "docker", "exec", "-i", "trading_postgres",
            "psql", "-U", "trading_admin", "-d", "trading_ai", "-c", sql
        ],
        check=True,
    )

def escape_json_for_sql(obj: dict) -> str:
    s = json.dumps(obj, ensure_ascii=False)
    return s.replace("'", "''")

def main() -> None:
    data = run_check()
    payload_sql = escape_json_for_sql(data)

    server_ok = data.get("connectivity", {}).get("server_time", {}).get("ok", False)
    ticker_ok = data.get("connectivity", {}).get("ticker_snapshot", {}).get("ok", False)
    health_state = "healthy" if (server_ok and ticker_ok and not data.get("issues")) else "degraded"

    status_sql = f"""
    INSERT INTO connector_runtime_status (
        connector_name,
        exchange_name,
        environment,
        mode,
        contract_version,
        health_state,
        write_enabled,
        permission_level,
        permission_label,
        last_successful_sync_time,
        last_error_time,
        last_error_summary,
        status_payload,
        notes
    ) VALUES (
        'bybit_connector_public_api',
        'bybit',
        'paper',
        'read_only',
        'v1',
        '{health_state}',
        false,
        0,
        'observer',
        NOW(),
        NULL,
        NULL,
        '{payload_sql}'::jsonb,
        'Public Bybit connectivity status written from public API connectivity check.'
    );
    """

    heartbeat_sql = f"""
    INSERT INTO connector_heartbeats (
        connector_name,
        exchange_name,
        environment,
        mode,
        health_state,
        heartbeat_payload,
        notes
    ) VALUES (
        'bybit_connector_public_api',
        'bybit',
        'paper',
        'read_only',
        '{health_state}',
        '{payload_sql}'::jsonb,
        'Public Bybit connectivity heartbeat written from public API connectivity check.'
    );
    """

    audit_sql = f"""
    INSERT INTO audit_events (
        event_source,
        event_type,
        severity,
        summary,
        event_details,
        notes
    ) VALUES (
        'bybit_connector',
        'public_connectivity_check_written',
        'info',
        'Bybit public connectivity check completed and persisted.',
        '{payload_sql}'::jsonb,
        'Audit event generated by public connectivity status writer.'
    );
    """

    psql_exec(status_sql)
    psql_exec(heartbeat_sql)
    psql_exec(audit_sql)

    print("bybit public connectivity status written successfully")

if __name__ == "__main__":
    main()
