#!/usr/bin/env python3
import json
import subprocess
from pathlib import Path

PREFLIGHT_SCRIPT = Path("/home/ncyu/srv/program_code/exchange_connectors/bybit_connector/scripts/bybit_readonly_preflight.py")

def run_preflight() -> dict:
    result = subprocess.run(
        ["python3", str(PREFLIGHT_SCRIPT)],
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(result.stdout)

def psql_exec(sql: str) -> None:
    subprocess.run(
        [
            "docker", "exec", "-i", "trading_postgres",
            "psql", "-U", "trading_admin", "-d", "trading_ai", "-c", sql
        ],
        check=True,
    )

def escape_json_for_sql(obj: dict) -> str:
    s = json.dumps(obj, ensure_ascii=False)
    return s.replace("'", "''")

def main() -> None:
    data = run_preflight()

    connector_name = data["connector_name"]
    exchange_name = data["exchange_name"]
    environment = data["environment"]
    mode = data["mode"]
    contract_version = data["contract_version"]
    write_enabled = "true" if data["write_enabled"] else "false"
    health_state = data["health_state"]
    payload_sql = escape_json_for_sql(data)

    status_sql = f"""
    INSERT INTO connector_runtime_status (
        connector_name,
        exchange_name,
        environment,
        mode,
        contract_version,
        health_state,
        write_enabled,
        permission_level,
        permission_label,
        last_successful_sync_time,
        last_error_time,
        last_error_summary,
        status_payload,
        notes
    ) VALUES (
        '{connector_name}',
        '{exchange_name}',
        '{environment}',
        '{mode}',
        '{contract_version}',
        '{health_state}',
        {write_enabled},
        0,
        'observer',
        NOW(),
        NULL,
        NULL,
        '{payload_sql}'::jsonb,
        'Connector runtime status written from local preflight.'
    );
    """

    heartbeat_sql = f"""
    INSERT INTO connector_heartbeats (
        connector_name,
        exchange_name,
        environment,
        mode,
        health_state,
        heartbeat_payload,
        notes
    ) VALUES (
        '{connector_name}',
        '{exchange_name}',
        '{environment}',
        '{mode}',
        '{health_state}',
        '{payload_sql}'::jsonb,
        'Connector heartbeat written from local preflight.'
    );
    """

    audit_sql = f"""
    INSERT INTO audit_events (
        event_source,
        event_type,
        severity,
        summary,
        event_details,
        notes
    ) VALUES (
        'bybit_connector',
        'connector_preflight_status_written',
        'info',
        'Bybit read-only preflight completed and status persisted.',
        '{payload_sql}'::jsonb,
        'Audit event generated by local connector preflight status writer.'
    );
    """

    psql_exec(status_sql)
    psql_exec(heartbeat_sql)
    psql_exec(audit_sql)

    print("bybit read-only preflight status written successfully")

if __name__ == "__main__":
    main()
